switch to mediaTypeV3 for ChecksRun Accept header
google/go-github pull request #1636
Opened 2020-10-02 23:27 UTC by n1lesh

switched Accept header's value to mediaTypeV3 from mediaTypeCheckRunsPreview. Since checks run is out of preview, didn't see any value in keeping the old preview constant. (github.go)

Followed as per,

Graduation of preview: https://developer.github.com/changes/2020-10-01-graduate-antiope-preview/
Docs: https://docs.github.com/en/free-pro-team@latest/rest/reference/checks

2020-10-02 23:50 UTC, gmlewis requested changes
Thank you, @n1lesh , but this is the wrong approach.
We need to literally remove it, not replace it.

Please see https://github.com/google/go-github/pull/1618/files as a recent example of how this is done.

2020-10-03 14:38 UTC, gmlewis approved these changes
Perfect!  Thank you, @n1lesh !
LGTM.

Awaiting second LGTM before merging.

2020-10-04 19:10 UTC, nightlark approved these changes
LGTM

2020-10-04 21:36 UTC, gmlewis commented
Thank you, @nightlark !
Merging.

2020-10-04 21:37 UTC, merged