Add support for Action Workflow state updates
google/go-github pull request #1638
Opened 2020-10-11 14:55 UTC by n1lesh

Fixes #1637  

Includes enable/disable by ID and Filename w/ tests included.

2020-10-11 15:05 UTC, gmlewis requested changes
This looks great, @n1lesh - just a few minor tweaks, please... mainly to help keep the auto-generated godocs to read nicely and be consistent with the rest of the repo.

2020-10-11 15:05 UTC, gmlewis commented on github/actions_workflows.go
> +// https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#enable-a-workflow
```suggestion
// GitHub API docs: https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#enable-a-workflow
```

2020-10-11 15:05 UTC, gmlewis commented on github/actions_workflows.go
> +// https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#disable-a-workflow
```suggestion
// GitHub API docs: https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#disable-a-workflow
```

2020-10-11 15:05 UTC, gmlewis commented on github/actions_workflows.go
> +// https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#disable-a-workflow
```suggestion
// GitHub API docs: https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#disable-a-workflow
```

2020-10-11 15:05 UTC, gmlewis commented on github/actions_workflows.go
> +// DisableWorkflowByID disables a workflow and sets the state of the workflow to disabled_manually
```suggestion
// DisableWorkflowByID disables a workflow and sets the state of the workflow to "disabled_manually".
```

2020-10-11 15:05 UTC, gmlewis commented on github/actions_workflows.go
> +// DisableWorkflowByFileName disables a workflow and sets the state of the workflow to disabled_manually
```suggestion
// DisableWorkflowByFileName disables a workflow and sets the state of the workflow to "disabled_manually".
```

2020-10-11 15:05 UTC, gmlewis commented on github/actions_workflows.go
> +func (s *ActionsService) DisableWorkflowByFileName(ctx context.Context, owner, repo string, workflowFileName string) (*Response, error) {
```suggestion
func (s *ActionsService) DisableWorkflowByFileName(ctx context.Context, owner, repo, workflowFileName string) (*Response, error) {
```

2020-10-11 16:11 UTC, gmlewis requested changes
Please revert the addition of ".DS_Store" to this PR.
In fact, if you want to add ".DS_Store" to the ".gitignore" file in this PR instead, that would prevent this from happening again.  Thanks.

2020-10-11 16:35 UTC, n1lesh commented
> Please revert the addition of ".DS_Store" to this PR.
> In fact, if you want to add ".DS_Store" to the ".gitignore" file in this PR instead, that would prevent this from happening again. Thanks.

Should have noticed this before committing. My apologies!

2020-10-11 16:51 UTC, gmlewis approved these changes
> Should have noticed this before committing. My apologies!

No problem!  Thank you, @n1lesh !
LGTM.

Awaiting second LGTM before merging.

2020-11-14 17:45 UTC, nightlark approved these changes
LGTM

2020-11-14 18:06 UTC, gmlewis commented
Thank you, @nightlark !
Merging.

2020-11-14 18:07 UTC, merged