Add Enterprise ListRunners/RegistrationToken APIs
google/go-github pull request #1644
Opened 2020-11-07 21:27 UTC by jamie-34254

2020-11-07 22:17 UTC, jamie-34254 commented
@googlebot I signed it!

2020-11-07 22:20 UTC, jamie-34254 commented
We just signed the corporate CLA, so I'm guessing there might be a delay on it?

2020-11-07 23:39 UTC, gmlewis commented
@googlebot is usually very fast. There might be an issue. Let's see if it responds with an update.

2020-11-08 22:28 UTC, jamie-34254 commented
@googlebot I signed it!

2020-11-09 13:28 UTC, gmlewis commented
> We just signed the corporate CLA, so I'm guessing there might be a delay on it?

Oh, I gotcha... I read that too quickly before.  Yes, there is a manual review process for brand new corporate CLAs... so we may have to wait a few days.

Thank you for your patience, @jamie-34254 !

2020-11-10 16:33 UTC, jamie-34254 commented
@googlebot I signed it!

2020-11-27 21:14 UTC, gmlewis requested changes
Thank you, @jamie-34254 - sorry for the delay, I didn't get a notification that the CLA issue had been resolved, unfortunately.

I have a couple questions if you could please clear them up for me.

2020-11-27 21:14 UTC, gmlewis commented on github/enterprise_actions_runners.go
> +	u := fmt.Sprintf("enterprises/%v/actions/runners/registration-token", enterprise)
When I follow the link on line 15, I see an endpoint like this:

```
POST /repos/{owner}/{repo}/actions/runners/registration-token
```

not the endpoint I see on line 17.  Why is that?

2020-11-27 21:14 UTC, gmlewis commented on github/enterprise_actions_runners.go
> +	u := fmt.Sprintf("enterprises/%v/actions/runners", enterprise)
There seems to be a mismatch here too.  The documentation link on line 35 points to an endpoint that looks like this:

```
GET /enterprises/{enterprise}/actions/runner-groups
```

and not the one listed on line 37.

2020-11-29 01:46 UTC, gmlewis approved these changes
Thank you, @jamie-34254 !
LGTM.

Once you fix the CLA problems (see comment about your email address), then this will be ready for a second LGTM and merging.

2020-11-29 17:39 UTC, jamie-34254 commented
Thanks @gmlewis! This should be good for 2nd review now :)

2020-12-02 14:14 UTC, wesleimp approved these changes
LGTM 👌🏼

2020-12-02 14:28 UTC, gmlewis commented
Thank you, @wesleimp !
Merging.

2020-12-02 14:28 UTC, merged