Add reactions preview to search service
google/go-github pull request #1818
Opened 2021-03-04 18:12 UTC by breathingdust

Currently the search service does not include the reactions preview media type header so issue searches do not include the reaction counts this preview provides. The issue struct already includes this [attribute](https://github.com/google/go-github/blob/b06cfbb1abc090e2ff47cac2f0d2d1750f847293/github/issues.go#L52) so adding this preview header is enough to populate it.

This PR adds that preview so this structure is populated.

2021-03-04 19:23 UTC, gmlewis requested changes
Thank you, @breathingdust !

Could you please add two new test methods in the `github/search_test.go` file to cover the new case?

* `TestSearchService_Issues`
* `TestSearchService_Issues_coverage`

2021-03-04 19:24 UTC, gmlewis approved these changes
Oh, never mind... I see we have these already.  Thanks.

LGTM.
Awaiting second LGTM before merging.

2021-03-05 12:32 UTC, wesleimp approved these changes
💙

2021-03-05 15:40 UTC, gmlewis commented
Thank you, @wesleimp !
Merging.

2021-03-05 15:40 UTC, merged