Support numeric public key ids for actions
google/go-github pull request #1836
Opened 2021-03-30 21:55 UTC by Azuka

closes #1835

2021-03-31 00:02 UTC, gmlewis requested changes
Thank you, @Azuka .
Please address the comments below.

2021-03-31 00:02 UTC, gmlewis commented on github/actions_secrets.go
> +		*p.KeyID = strconv.FormatFloat(v, 'f', -1, 64)
Why not just get rid of line 37?

```suggestion
		p.KeyID = String(strconv.FormatFloat(v, 'f', -1, 64))
```

2021-03-31 00:02 UTC, gmlewis commented on github/actions_secrets.go
> +func (p *PublicKey) UnmarshalJSON(data []byte) error {
This method needs a godoc comment describing its use.

2021-03-31 00:02 UTC, gmlewis commented on github/actions_secrets.go
> +		return err
This line should be covered in a unit test that provides it with garbage data.

2021-03-31 04:46 UTC, Azuka commented on github/actions_secrets.go
> +		*p.KeyID = strconv.FormatFloat(v, 'f', -1, 64)
That was pretty obvious. Thanks!

2021-03-31 04:49 UTC, Azuka commented
@gmlewis thanks for reviewing. I've made the suggested changes

2021-03-31 12:55 UTC, gmlewis requested changes

2021-03-31 12:55 UTC, gmlewis commented on github/actions_secrets.go
> +// do not error out when unmarshaling
```suggestion
// do not error out when unmarshaling.
```

2021-03-31 12:55 UTC, gmlewis commented on github/actions_secrets_test.go
> +		"Empty": {
Can you please add four more test cases?

```go
"Nil": {
  data: nil,
  ...
},
"Empty String": {
  data: []byte(""),
  ...
},
"Missing Key": {
  data: []byte(`{"key_id":"1234"}`),
  ...
},
"Missing KeyID": {
  data: []byte(`{"key":"2Sg8iYjAxxmI2LvUXpJjkYrMxURPc8r+dB7TJyvv1234"}`),
  ...
},
```

2021-03-31 12:55 UTC, gmlewis commented on github/actions_secrets_test.go
> +			data:          []byte(`{"key_id":"1234","key":"2Sg8iYjAxxmI2LvUXpJjkYrMxURPc8r+dB7TJyvv1234"}`),
This test case says "Numeric KeyID" but the "key_id" field is not numeric.  Could you please fix this?

2021-03-31 12:55 UTC, gmlewis commented on github/actions_secrets_test.go
> +			data:          []byte(`{"key_id":1234,"key":"2Sg8iYjAxxmI2LvUXpJjkYrMxURPc8r+dB7TJyvv1234"}`),
This test case says "String KeyID" but the "key_id" field is not a string.  Could you please fix this?

2021-03-31 21:23 UTC, gmlewis commented
> I'm really sorry, I missed that.

No problem.  Next time.  :joy:

2021-03-31 21:25 UTC, gmlewis approved these changes
Thank you, @Azuka !
LGTM.

Awaiting second LGTM before merging.

2021-04-01 13:29 UTC, wesleimp approved these changes
💙

2021-04-01 14:15 UTC, gmlewis commented
Thank you, @wesleimp .
Merging.

2021-04-01 14:16 UTC, merged