Add support for the list failed organization invitations feature
google/go-github pull request #1871
Opened 2021-05-08 15:05 UTC by itsmatinx

Resolves #1812

2021-05-08 15:31 UTC, gmlewis requested changes
Thank you, @itsmatinx !
Just a few minor tweaks, please, and also please run `go generate ./...` and push the changes (please do not _force_ push) to this PR (as described in our `CONTRIBUTING.md` doc).

2021-05-08 15:31 UTC, gmlewis commented on github/orgs_members.go
> +// Github API docs: https://docs.github.com/en/rest/reference/orgs#list-failed-organization-invitations
```suggestion
// GitHub API docs: https://docs.github.com/en/rest/reference/orgs#list-failed-organization-invitations
```

2021-05-08 15:31 UTC, gmlewis commented on github/orgs_members.go
> +// ListFailedOrgInvitation returns a list of failed inviatations.
```suggestion
// ListFailedOrgInvitations returns a list of failed inviatations.
```

2021-05-08 15:31 UTC, gmlewis commented on github/orgs_members_test.go
> +func TestOrganizationsService_ListFailedOrgInvitation(t *testing.T) {
```suggestion
func TestOrganizationsService_ListFailedOrgInvitations(t *testing.T) {
```

2021-05-08 20:04 UTC, itsmatinx commented
> Thank you, @itsmatinx !
> Just a few minor tweaks, please, and also please run `go generate ./...` and push the changes (please do not _force_ push) to this PR (as described in our `CONTRIBUTING.md` doc).

Thank you for reviewing the PR. I read the `CONTRIBUTING.md` previously, but I misunderstood the generated files. I thought it would be enough to run `go generate ./...` and simply make sure everything works.

The requested changes have also been resolved.

2021-05-08 20:07 UTC, gmlewis approved these changes
Thank you, @itsmatinx !
LGTM.

Awaiting second LGTM before merging.

2021-05-12 12:48 UTC, wesleimp approved these changes
💙

2021-05-12 13:28 UTC, gmlewis commented
Thank you, @wesleimp !
Merging.

2021-05-12 13:28 UTC, merged