editChange event: define struct types instead of using anonymous structs
google/go-github pull request #1900
Opened 2021-06-18 12:59 UTC by fho

The types of the fields of the EditChange struct were defined inline as
anonymous structs.
This made it tedious to use the EditChange struct in testcases, because
the anonymous type needed to be redefined (incl the exact same JSON
tags) whenever it was assigned. The TestEdit* testcases are good example
for it.

Using anonymous struct also does not scale well when the struct changes.
For example when a field is added to an anonymous struct, every place
where the anonymous struct is assigned must also be changed.

Another advantage of using regular types is that accessors  will be
generated automatically and can be used instead of having to manually
check for nil values when accessing the struct fields.

Define the types as regular structs in event_types.go instead.

2021-06-18 14:07 UTC, gmlewis requested changes
While you are here, do you want to do the same thing for:

* `ProjectChange`
* `ProjectCardChange`
* `ProjectColumnChange`
* `TeamChange`
* `RepositoryVulnerabilityAlertEvent`

?

2021-06-18 14:07 UTC, gmlewis commented on github/event_types.go
> +// EditBase represents a ref change of a pull-request.
```suggestion
// EditRef represents a ref change of a pull-request.
```

2021-06-18 14:07 UTC, gmlewis commented on github/event_types.go
> +// EditBase represents a sha change of a pull-request.
```suggestion
// EditSHA represents a sha change of a pull-request.
```

2021-06-18 15:02 UTC, fho commented
@gmlewis I also replaced the other anonymous struct types.

2021-06-18 15:32 UTC, gmlewis approved these changes
Thank you, @fho !
LGTM.

Awaiting second LGTM before merging.

2021-06-18 15:32 UTC, gmlewis commented
Also, @fho - could you please remove the "Draft" setting when you are ready?

2021-06-18 15:41 UTC, fho commented
@gmlewis I'll remove the draft status as soon as my employer signed the CA, probably beginning of next week. I only noticed that it was missing after I created it. :-)

2021-06-18 15:44 UTC, gmlewis commented
> @gmlewis I'll remove the draft status as soon as my employer signed the CA, probably beginning of next week. I only noticed that it was missing after I created it. :-)

Interesting - the googlebot marked the PR as having passed the CLA test.  OK, sounds good.

2021-06-18 18:07 UTC, fho commented
> > @gmlewis I'll remove the draft status as soon as my employer signed the CA, probably beginning of next week. I only noticed that it was missing after I created it. :-)
> 
> Interesting - the googlebot marked the PR as having passed the CLA test. OK, sounds good.

It's because I signed the PR for myself already in the past.

2021-06-29 07:20 UTC, fho commented
@gmlewis my employer signed the CLA now also.
I can't see it on https://cla.developers.google.com/clas for my account but I'm in the contributors google-group of the CLA.

2021-06-29 14:35 UTC, gmlewis commented
Friendly ping, @wesleimp

2021-07-07 16:04 UTC, sagar23sj commented
If we are expecting to replace all anonymous structs with defined struct types, then I guess a few are still missing in this PR.
I am listing them below :
1. File: github.go / ErrorResponse
2. File: activity.go / Feeds

@gmlewis

2021-07-08 08:15 UTC, fho commented
@sagar23sj thanks, I'll update the PR and also replace those anonymous structs.

It was not my initial intent of the PR to replace all anonymous structs but it makes sense to have a consistent solution

2021-07-08 08:55 UTC, fho commented
done

2021-07-08 13:45 UTC, gmlewis approved these changes
Thank you, @fho !
LGTM.

Awaiting second LGTM before merging.

2021-07-08 17:31 UTC, Parker77 approved these changes
LGTM.

2021-07-08 17:52 UTC, gmlewis commented
@fho  - would you like to resolve the merge conflicts, or would you like me to do that?  I'm fine either way.

2021-07-08 18:03 UTC, fho commented
@gmlewis also both fine with me, feel free to do changes :-)
Otherwise I can solve the conflict tomorrow

2021-07-08 19:35 UTC, merged