Add test for JSON marshalling for Teams
google/go-github pull request #1941
Opened 2021-07-07 11:49 UTC by emiscode

Resource covered: Teams

2021-07-07 14:17 UTC, gmlewis requested changes
Thank you, @emiscode !
Just a couple minor tweaks, please.

2021-07-07 14:17 UTC, gmlewis commented on github/teams_test.go
> +
Please delete this blank line and add one immediately before the `want` below.

2021-07-07 14:17 UTC, gmlewis commented on github/teams_test.go
> +	testJSONMarshal(t, u, want)
For consistency with the rest of the repo, please add a blank line before this one.

2021-07-07 15:17 UTC, gmlewis approved these changes
Thank you, @emiscode !
LGTM.

In future PRs, please do not use force-push, as it makes it more difficult to review changes made since the last code review.  We always use squash-and-merge in this repo, so you can push as many commits as necessary, and they will be merged into one final commit.

Awiating second LGTM before merging.

2021-07-07 15:18 UTC, gmlewis requested changes
Whups, it looks like the code needs to be run through `gofmt` first, in order for the tests to pass.  Please fix.

2021-07-07 15:49 UTC, gmlewis approved these changes
Thank you, @emiscode !
LGTM.

Awaiting second LGTM before merging.

2021-07-07 15:55 UTC, emiscode commented
Thank you @gmlewis!

I'm glad to be contributing to this project, and I really appreciated your care with details during your review process.

2021-07-08 17:50 UTC, Parker77 approved these changes
LGTM.

2021-07-08 20:38 UTC, merged