Add test cases for JSON resource marshaling
google/go-github pull request #1967
Opened 2021-07-12 07:34 UTC by sagar23sj

Resources Covered :
- GistFile

Helps with issue: #55

2021-07-12 11:07 UTC, gmlewis requested changes
Thank you, @sagar23sj !
One minor tweak, please.

2021-07-12 11:07 UTC, gmlewis commented on github/gists_test.go
> +func TestGistFile_marshall(t *testing.T) {
```suggestion
func TestGistFile_Marshal(t *testing.T) {
```

2021-07-12 11:25 UTC, sagar23sj commented on github/gists_test.go
> +func TestGistFile_marshall(t *testing.T) {
Updated @gmlewis

2021-07-12 12:52 UTC, gmlewis approved these changes
Thank you, @sagar23sj !
LGTM.

Awaiting second LGTM before merging.

2021-07-13 16:14 UTC, Parker77 approved these changes
LGTM.

2021-07-13 17:11 UTC, merged