Add test cases for JSON resource marshaling
google/go-github pull request #1988
Opened 2021-07-12 18:26 UTC by sagar23sj

Resources Covered :

- ServiceHook
- CodeOfConduct
- markdownRequest

Helps with issue: #55

2021-07-12 19:18 UTC, gmlewis requested changes

2021-07-12 19:18 UTC, gmlewis commented on github/misc_test.go
> +func TestMarkdownRequest_marshal(t *testing.T) {
```suggestion
func TestMarkdownRequest_Marshal(t *testing.T) {
```

2021-07-12 19:18 UTC, gmlewis commented on github/misc_test.go
> +func TestCodeOfConduct_marshal(t *testing.T) {
```suggestion
func TestCodeOfConduct_Marshal(t *testing.T) {
```

2021-07-12 19:18 UTC, gmlewis commented on github/misc_test.go
> +func TestServiceHook_marshal(t *testing.T) {
```suggestion
func TestServiceHook_Marshal(t *testing.T) {
```

2021-07-12 20:45 UTC, gmlewis approved these changes
Thank you, @sagar23sj !
LGTM.

Awaiting second LGTM before merging.

2021-07-13 18:15 UTC, Parker77 approved these changes
LGTM.

2021-07-13 18:51 UTC, merged