Add methods to add and remove repos for actions on org level
google/go-github pull request #1997
Opened 2021-07-14 15:09 UTC by FloThinksPi

This commit adds the abillity to add one or more repositories to the
list of enabled repositories for github actions on org level.
It also adds the abillity to remove them from this list.
With this change we can now enable and disable repos to use github actions on org level.

The used endpoints for this are:
https://docs.github.com/en/rest/reference/actions#set-selected-repositories-enabled-for-github-actions-in-an-organization
https://docs.github.com/en/rest/reference/actions#disable-a-selected-repository-for-github-actions-in-an-organization

fixes #1995

2021-07-14 16:16 UTC, gmlewis requested changes
Thanks, @FloThinksPi , but this PR appears to have a few problems.
Did you try out these two new methods before submitting the PR?

I ask because one of the signatures doesn't match the official documentation and I'm not sure how it could have worked.

2021-07-14 16:16 UTC, gmlewis commented on github/actions_runners.go
> +// RemoveEnabledReposInOrg removes a single repositorie from the list of enabled repos for GitHub Actions in an organization.
```suggestion
// RemoveEnabledRepoInOrg removes a single repository from the list of enabled repos for GitHub Actions in an organization.
```

2021-07-14 16:16 UTC, gmlewis commented on github/actions_runners.go
> +// GitHub API docs: https://docs.github.com/en/rest/reference/actions#enable-a-selected-repository-for-github-actions-in-an-organization
```suggestion
// GitHub API docs: https://docs.github.com/en/rest/reference/actions#set-selected-repositories-enabled-for-github-actions-in-an-organization
```

2021-07-14 16:16 UTC, gmlewis commented on github/actions_runners.go
> +		Repository_id []int64 `json:"repository_id"`
```suggestion
		IDs []int64 `json:"selected_repository_ids"`
```

2021-07-14 16:16 UTC, gmlewis commented on github/actions_runners.go
> +	}{Repository_id: repositoryIDs})
```suggestion
	}{IDs: repositoryIDs})
```

2021-07-14 16:16 UTC, gmlewis commented on github/actions_runners_test.go
> +
Please delete this blank line for consistency with the rest of the repo.

2021-07-14 16:16 UTC, gmlewis commented on github/actions_runners_test.go
> +
ditto

2021-07-14 17:31 UTC, FloThinksPi commented
Woh thanks @gmlewis  for the super quick review. 
I just wanted to display the diff and must have opened it already. Didnt run it yet at all, just the tests. 
I will include your suggestions and try it out.

2021-07-14 17:47 UTC, FloThinksPi commented
@googlebot I signed it!

2021-07-14 17:51 UTC, gmlewis commented
Hi @FloThinksPi - it looks like the tests need updating:

```
=== RUN   TestActionsService_AddEnabledReposInOrg
    actions_runners_test.go:411: request Body is {"selected_repository_ids":[123,1234]}
        , want {"repository_id":[123,1234]}
--- FAIL: TestActionsService_AddEnabledReposInOrg (0.00s)
```

2021-07-14 17:53 UTC, gmlewis commented
@googlebot I consent.

2021-07-14 19:24 UTC, FloThinksPi commented
@gmlewis Yea all done now 👍🏼 . I also renamed the AddEnableReposInOrg method to SetEnabledReposInOrg since the used endpoint sets the list absolute. I thus added the https://docs.github.com/en/rest/reference/actions#enable-a-selected-repository-for-github-actions-in-an-organization endpoint which is now AddEnableReposInOrg which appends to the list of enabled repos.

All tests return ok and i tested all three methods against a GitHubEnterprise 3.0 Instance.

2021-07-14 19:44 UTC, gmlewis commented
> Should i squash the commits ?

You don't need to squash, as we only "Squash and merge" in this repo anyway.

I'll check the names now.

2021-07-14 19:46 UTC, gmlewis approved these changes
Thank you, @FloThinksPi !
LGTM.

Awaiting second LGTM before merging.

2021-07-15 18:54 UTC, wesleimp approved these changes

2021-07-15 19:30 UTC, gmlewis commented
Thank you, @wesleimp !
Merging.

2021-07-15 19:30 UTC, merged