Mock transport with pc frames
google/go-github pull request #2008
Opened 2021-07-16 14:25 UTC by migueleliasweb

2021-07-16 14:29 UTC, migueleliasweb commented
I've added the code generation to all methods now. Let me know your thoughts @gmlewis :+1: .

2021-07-16 16:12 UTC, gmlewis requested changes
Thank you, @migueleliasweb .  I'm liking this approach.
You will also want to add a new generator to this PR here:
https://github.com/google/go-github/blob/master/github/github.go#L6-L7

2021-07-16 16:12 UTC, gmlewis commented on mock/gen/gen-request-matches.go
> +		return
Please delete this `return` line.

2021-07-16 16:12 UTC, gmlewis commented on mock/gen/gen-request-matches.go
> +			if fn, ok := decl.(*ast.FuncDecl); ok {
```suggestion
			fn, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}

```

2021-07-16 16:12 UTC, gmlewis commented on mock/gen/gen-request-matches.go
> +				if receiverType, ok := fn.Recv.List[0].Type.(*ast.StarExpr); ok {
```suggestion
				receiverType, ok := fn.Recv.List[0].Type.(*ast.StarExpr)
				if !ok {
					continue
				}

```

2021-07-16 16:12 UTC, gmlewis commented on mock/gen/gen-request-matches.go
> +					if receiverTypeIndent, ok := receiverType.X.(*ast.Ident); ok {
```suggestion
					receiverTypeIndent, ok := receiverType.X.(*ast.Ident)
					if !ok || receiverTypeIndent.Name == "" {
						continue
					}

```

2021-07-16 16:12 UTC, gmlewis commented on mock/gen/gen-request-matches.go
> +						if receiverTypeIndent.Name != "" {
This line can then be deleted if you take my suggestions above.

2021-07-16 16:12 UTC, gmlewis commented on mock/gen/gen-request-matches.go
> +								strings.Replace(
After the reduction in indentation above, this `strings.Replace` could all fit nicely on a single line.

2021-07-16 16:12 UTC, gmlewis commented on mock/gen/gen-request-matches.go
> +	// fmt.Println("requestMatches:", requestMatches)
Please remove this debugging line.

2021-07-16 16:12 UTC, gmlewis commented on mock/gen/gen-request-matches.go
> +	buf := bytes.NewBufferString("")
```suggestion
	var buf bytes.Buffer
```

2021-07-16 16:12 UTC, gmlewis commented on mock/gen/gen-request-matches.go
> +		buf,
```suggestion
		&buf,
```

2021-07-16 19:28 UTC, gmlewis commented
After further consideration, I think that @willnorris is correct in his [comment](https://github.com/google/go-github/pull/1980#issuecomment-881619560) that this would be a great utility to place in an external helper repo.

So my recommendation is that we close this PR and also close #1800 and point to a new helper repo in this repo's README.md once it has been implemented.

2021-07-17 05:47 UTC, migueleliasweb commented
Thanks @gmlewis for the extensive review!

I left a comment in the initial PR (https://github.com/google/go-github/pull/1980) so you and Will can talk more. I will wait until the decision is made to move this to a new repo or not before proceeding with the rest of the implementation.

2021-07-27 12:22 UTC, closed without merging