fix derecated field
google/go-github pull request #2017
Opened 2021-07-21 05:28 UTC by ganeshkumarsv

The deprecated field `open` got changed to `state` to hold 3 different values (`open, dismissed, and fixed`)

2021-07-21 13:16 UTC, gmlewis approved these changes
Thank you, @ganeshkumarsv !
LGTM.

Awaiting second LGTM due to breaking API change.

2021-07-26 18:23 UTC, ganeshkumarsv commented
@gmlewis @wesleimp Gentle bump

2021-07-30 15:04 UTC, gmlewis requested changes

2021-07-30 15:04 UTC, gmlewis commented on github/code-scanning.go
> +	SeverityLevel   *string  `json:"security_severity_level,omitempty"`
For consistency, can we please change the name?

```suggestion
	SecuritySeverityLevel   *string  `json:"security_severity_level,omitempty"`
```

2021-07-30 19:47 UTC, gmlewis approved these changes

2021-08-06 02:11 UTC, ganeshkumarsv commented
@gmlewis @wesleimp gentle bump

2021-08-06 14:29 UTC, Parker77 approved these changes
LGTM.

2021-08-06 14:37 UTC, merged

2021-08-10 20:29 UTC, ganeshkumarsv commented
@gmlewis Thank you for approving & merging the PR. Can I know when the next release will be created for go-github?

2021-08-10 21:37 UTC, gmlewis commented
> @gmlewis Thank you for approving & merging the PR. Can I know when the next release will be created for go-github?

No problem. I should be able to cut a new release by tomorrow.

2021-08-10 21:54 UTC, ganeshkumarsv commented
awesome! Thank you!

2021-08-11 11:21 UTC, gmlewis commented
@ganeshkumarsv - [v38](https://pkg.go.dev/github.com/google/go-github/v38/github) has now been released.