Update PingEvent type
google/go-github pull request #2018
Opened 2021-07-21 07:55 UTC by pecigonzalo

The `ping` event has changed or is different than what is declared in the current
code. Updating it to match https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#ping.

2021-07-21 07:59 UTC, pecigonzalo commented
@googlebot I signed it!

2021-07-21 13:26 UTC, gmlewis requested changes
Thank you, @pecigonzalo - please run `go generate ./...` and push (not force-push) the changes to this PR in order to make the tests pass.

For more info, this process has been discussed in our `CONTRIBUTING.md` file at the top of this repo.

2021-07-21 14:19 UTC, pecigonzalo commented
@gmlewis Thanks I missed the `// Code generated by gen-accessors; DO NOT EDIT.` as I jumped directly to the definition.

2021-07-21 14:36 UTC, gmlewis approved these changes
Thank you, @pecigonzalo !
LGTM.

Awaiting second LGTM due to breaking API change.

2021-07-21 14:37 UTC, pecigonzalo commented
@gmlewis There seems to be a bunch of these APIs that are outdated, Ill take a stab at updating a few more later on.

2021-07-21 14:41 UTC, gmlewis commented
> @gmlewis There seems to be a bunch of these APIs that are outdated, Ill take a stab at updating a few more later on.

Thank you, @pecigonzalo!

> It also seems like GH is quite inconsistent in the way it sends events. eg. `ping` for Installations and for Webhooks are different, but they reference the same event documentation.

Yes, and if I remember correctly, some structs are used in multiple scenarios, so we want to be careful to avoid removing fields that might still be used occasionally.

2021-07-21 23:00 UTC, gmlewis commented
What the heck is pull-bot and why did it force push ?!?

2021-07-21 23:02 UTC, gmlewis requested changes
pull-bot ?!?

2021-07-22 06:16 UTC, pecigonzalo commented
Oh crap, I should have opened this from  a branch. Pull-bot is a bot to keep my forks in sync with upstream https://github.com/wei/pull. 

Ill send a new PR from a branch.

2021-07-26 11:13 UTC, merged