Add TokenExpiration to Rsponce
google/go-github pull request #2031
Opened 2021-08-05 16:51 UTC by w-haibara

GitHub has been updated to allow you to set the expiration date of your personal access token. And the expiration date is now displayed in the `GitHub-Authentication-Token-Expiration` header of the GItHub API. 
https://github.blog/changelog/2021-07-26-expiration-options-for-personal-access-tokens/

This PR add `TokenExpiration` field to Response.

2021-08-05 17:13 UTC, gmlewis requested changes
Thank you, @w-haibara !

In addition to the comments below, please add a new unit test for the new `parseTokenExpiration` function.

Also please make sure to run `gofmt` on the edited files so that their formatting is standardized.

See CONTRIBUTING.md in the top-level of this repo for more information.

2021-08-05 17:13 UTC, gmlewis commented on example/tokenauth/main.go
> +		log.Printf("Token Expiration: %v\n", resp.TokenExpiration.String())
```suggestion
		log.Printf("Token Expiration: %v\n", resp.TokenExpiration)
```

2021-08-05 17:13 UTC, gmlewis commented on github/github.go
> +		t, _ := time.Parse("2006-01-02 03:04:05 MST", v)
```suggestion
		if t, err := time.Parse("2006-01-02 03:04:05 MST", v); err == nil {
			exp = Timestamp{t.Local()}
		}
```

2021-08-06 02:47 UTC, w-haibara commented
Hi, @gmlewis ! Thanks for the thoughtful review.
I've fixed the areas you commented on and added a test. I apologize again for the unformatted commits. I've fixed that as well.

2021-08-06 12:58 UTC, gmlewis requested changes
Thank you, @w-haibara !

2021-08-06 12:58 UTC, gmlewis commented on github/github_test.go
> +			header: "2021-09-03 02:34:04 UTC",
Can you please add one more test with a completely garbage header and show how it behaves in that case?

2021-08-06 12:58 UTC, gmlewis commented on github/github_test.go
> +			res: &http.Response{
Since `res` starts out the same in every test case, you can remove it from this struct and initialize a new fresh one below within the test loop.

2021-08-06 13:26 UTC, gmlewis approved these changes
Thank you, @w-haibara !
LGTM.

Awaiting second LGTM before merging.

2021-08-06 13:42 UTC, w-haibara commented
Thank you, @gmlewis.
This is almost the first OSS contributor for me. Your review has helped me a lot!

2021-08-06 13:57 UTC, gmlewis commented
> Thank you, @gmlewis.
> This is almost the first OSS contributor for me. Your review has helped me a lot!

Thank you, for your contributions, @w-haibara !  Your help is greatly appreciated!

2021-08-06 14:33 UTC, Parker77 approved these changes
LGTM!

2021-08-06 14:37 UTC, merged