Added function for redelivering webhooks #2060
google/go-github pull request #2061
Opened 2021-08-24 15:34 UTC by DeviousLab

Aims to resolve issue #2060. Let me know if I've done it wrong!

Signed-off-by: DeviousLab <deviouslab@gmail.com>

2021-08-24 15:40 UTC, gmlewis requested changes
Thank you, @DeviousLab !
This is a good start. Please add a new unit test for the new method and make sure to run `gofmt` on your added code.

2021-08-24 15:41 UTC, gmlewis commented on github/orgs_hooks_deliveries.go
> +	req, err := s.client.NewRequest("GET", u, nil)
```suggestion
	req, err := s.client.NewRequest("POST", u, nil)
```

2021-08-25 14:16 UTC, gmlewis approved these changes
Thank you, @DeviousLab !
LGTM.

Awaiting second LGTM before merging.

2021-09-03 16:24 UTC, Parker77 approved these changes
LGTM.

2021-09-03 16:26 UTC, gmlewis commented
Thank you, @Parker77 !
Merging.

2021-09-03 16:26 UTC, merged