Handle protection status errors for unprotected branches
google/go-github pull request #2092
Opened 2021-09-13 04:40 UTC by hemachandarv

Resolves #625

2021-09-13 04:43 UTC, hemachandarv commented
@gmlewis I've addressed #625 by returning an explicit error in the `GET` APIs. Do you think this is a good idea?

Also, do you think we should cover the same for the `POST` APIs too?

2021-09-13 12:01 UTC, gmlewis requested changes
Thank you, @hemachandarv !
Just a few minor tweaks, please.

2021-09-13 13:21 UTC, hemachandarv commented on github/repos_test.go
> +			"message": "Branch not protected",
@gmlewis I'm not sure if we'll be able to use a variable inside a raw string. Am I missing something..?

2021-09-13 13:23 UTC, hemachandarv commented on github/repos.go
> +	return false
@gmlewis Thank you for suggesting this change. I certainly missed this simplification.

2021-09-13 14:01 UTC, gmlewis commented on github/repos_test.go
> +			"message": "Branch not protected",
Whups, you are correct. Please use `%v` and the variable name in that case.

2021-09-13 14:19 UTC, hemachandarv commented on github/repos_test.go
> +			"message": "Branch not protected",
Thanks @gmlewis. I've updated the PR with the suggested changes.

2021-09-13 15:19 UTC, gmlewis approved these changes
Thank you, @hemachandarv !
LGTM.

Awaiting second LGTM before merging.

2021-12-03 13:51 UTC, cpanato approved these changes
LGTM
thanks!

2021-12-03 14:47 UTC, gmlewis commented
Thank you, @cpanato !
Merging.

2021-12-03 14:47 UTC, merged