Add support for apps webhook config endpoints
google/go-github pull request #2096
Opened 2021-09-15 09:02 UTC by rpelliard

This adds support for two Apps API endpoints (see #2095)
- [Get a webhook configuration for an app](https://docs.github.com/en/rest/reference/apps#get-a-webhook-configuration-for-an-app)
- [Update a webhook configuration for an app](https://docs.github.com/en/rest/reference/apps#update-a-webhook-configuration-for-an-app)

Both endpoints require authentication as an app (with a JWT), which can be dealt with by the underlying transport.

A few notes:
- I reused / extended the `HookConfig` struct which was defined in `orgs_audit_logs.go`, since it represents the same object.

- The `InsecureSSL` field of the struct is a `*string`. However, GitHub only returns `"0"` or `"1"` (insecure SSL disabled / enabled), so I think it'd be more user-friendly to use a `*bool`, and write some logic so that boolean values are correctly (un)marshaled from `"0"`/`"1"`. I'd be happy to write the code to deal with this, but that would be a breaking change so I wanted to check with you first.

- This is probably out of scope of this PR, but the [`Hook` struct](https://github.com/google/go-github/blob/master/github/repos_hooks.go#L87) used for repository / organization webhooks endpoints is using a `map[string]interface{}` for the `Config` field, but I think it could be using the `HookConfig` struct as well since it represents the same object. Happy to make that change in a separate PR, but this would be a breaking change as well.

2021-09-15 12:04 UTC, gmlewis requested changes
Thank you, @rpelliard !
One tiny nit to fix, please, but otherwise LGTM.

Awaiting second LGTM before merging.

2021-09-15 12:04 UTC, gmlewis commented on github/orgs_audit_log.go
> +	// Secret is returned obfuscated by GitHub, but it can be set for outgoing requests
```suggestion
	// Secret is returned obfuscated by GitHub, but it can be set for outgoing requests.
```

2021-09-15 13:10 UTC, gmlewis approved these changes
LGTM.

Awaiting second LGTM before merging.

2021-09-29 11:49 UTC, rpelliard commented
Hello @gmlewis @wesleimp, do you know when we'd be able to merge this ?

2021-09-29 14:01 UTC, gmlewis commented
> Hello @gmlewis @wesleimp, do you know when we'd be able to merge this ?

Maybe @Parker77 has time to take a look at this one.

2021-09-29 14:03 UTC, gmlewis commented on github/apps_hooks.go
> +package github
```suggestion
// Copyright 2021 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package github
```

No need for action... I'll add this required header.

2021-09-29 14:03 UTC, gmlewis commented on github/apps_hooks_test.go
> +package github
```suggestion
// Copyright 2021 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package github
```

No need for action... I'll add this required header.

2021-09-29 14:17 UTC, Parker77 approved these changes
One minor nit, otherwise LGTM.

2021-09-29 14:17 UTC, Parker77 commented on github/doc.go
> +It supports both authentication as an installation, using an installation access token
```suggestion
It supports both authentication as an installation, using an installation access token,
```

2021-09-29 14:20 UTC, Parker77 commented
@googlebot I fixed it.

2021-09-29 14:21 UTC, gmlewis commented
> One minor nit, otherwise LGTM.

Thank you, @Parker77 !
Merging.

2021-09-29 14:21 UTC, merged