feat: added BranchProtectionRuleEvent
google/go-github pull request #2102
Opened 2021-09-22 00:36 UTC by bhogatemadhura

2021-09-22 03:38 UTC, bhogatemadhura commented
@googlebot I signed it!

2021-09-22 13:23 UTC, gmlewis requested changes
Thank you, @bhogatemadhura .
Please address the following issues.

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	DismissStaleReviewsonPush          bool       `json:"dismiss_stale_reviews_on_push"`
```suggestion
	DismissStaleReviewsOnPush          *bool       `json:"dismiss_stale_reviews_on_push,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +type ProtectionRules struct {
Please add godoc comment for this struct and make it singular to match the `"rule"` usage.

```suggestion
type ProtectionRule struct {
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	RequiredApprovingReviewCount       int        `json:"required_approving_review_count"`
```suggestion
	RequiredApprovingReviewCount       *int        `json:"required_approving_review_count,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	RequireCodeOwnerReviews            bool       `json:"require_code_owner_reviews,omitempty"`
```suggestion
	RequireCodeOwnerReview            *bool       `json:"require_code_owner_review,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	AuthorizedDismissalActors          bool       `json:"authorized_dismissal_actors_only"`
```suggestion
	AuthorizedDismissalActorsOnly          *bool       `json:"authorized_dismissal_actors_only,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	IgnoreApprovalsFromContributors    bool       `json:"ignore_approvals_from_contributors"`
```suggestion
	IgnoreApprovalsFromContributors    *bool       `json:"ignore_approvals_from_contributors,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	StatusChecksEnforcementLevel       *string    `json:"required_status_checks_enforcement_level,omitempty"`
```suggestion
	RequiredStatusChecksEnforcementLevel       *string    `json:"required_status_checks_enforcement_level,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	StrictRequiredStatusChecksPolicy   bool       `json:"strict_required_status_checks_policy"`
```suggestion
	StrictRequiredStatusChecksPolicy   *bool       `json:"strict_required_status_checks_policy,omitempty"`
	SignatureRequirementEnforcementLevel   *string       `json:"signature_requirement_enforcement_level,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	LinearHistoryEnforcementLevel      *string    `json:"linear_history_requirement_enforcement_level,omitempty"`
```suggestion
	LinearHistoryRequirementEnforcementLevel      *string    `json:"linear_history_requirement_enforcement_level,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	AdminEnforced                      bool       `json:"admin_enforced"`
```suggestion
	AdminEnforced                      *bool       `json:"admin_enforced,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	ForcePushesEnforcementLevel        *string    `json:"allow_force_pushes_enforcement_level,omitempty"`
```suggestion
	AllowForcePushesEnforcementLevel        *string    `json:"allow_force_pushes_enforcement_level,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	DeletionsEnforcementLevel          *string    `json:"allow_deletions_enforcement_level,omitempty"`
```suggestion
	AllowDeletionsEnforcementLevel          *string    `json:"allow_deletions_enforcement_level,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	DeploymentEnforcementLevel         *string    `json:"required_deployments_enforcement_level,omitempty"`
```suggestion
	RequiredDeploymentsEnforcementLevel         *string    `json:"required_deployments_enforcement_level,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	ConversationResolutionLevel        *string    `json:"required_conversation_resolution_level,omitempty"`
```suggestion
	RequiredConversationResolutionLevel        *string    `json:"required_conversation_resolution_level,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	AuthorizedActorsOnly               bool       `json:"authorized_actors_only"`
```suggestion
	AuthorizedActorsOnly               *bool       `json:"authorized_actors_only,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +// If the BranchProtection was edited, the changes to the rule
```suggestion
// ProtectionChanges represents the changes to the rule if the BranchProtection was edited.
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	AuthorizedActorsOnly *AuthorizedActorsOnly `json:"authorized_actors_only"`
```suggestion
	AuthorizedActorsOnly *AuthorizedActorsOnly `json:"authorized_actors_only,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	From bool `json:"from"`
```suggestion
	From *bool `json:"from,omitempty"`
```

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +type AuthorizedActorsOnly struct {
Please add godoc comment.

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +type AuthorizedActorNames struct {
Please add godoc comment.

2021-09-22 13:23 UTC, gmlewis commented on github/repos.go
> +	From []string `json:"from"`
```suggestion
	From []string `json:"from,omitempty"`
```

2021-09-22 16:42 UTC, bhogatemadhura commented on github/repos.go
> +type ProtectionRule struct {
Apparently there is already `ProtectionRule` already defined here - 

https://github.com/google/go-github/blob/7a077bbd7313615d4f924f12b065913ee94e1d58/github/repos_environments.go#L52

May be I will name as `BranchProtectionRule` here

2021-09-22 17:25 UTC, gmlewis requested changes
Thank you, @bhogatemadhura !
One minor tweak, please, then LGTM.

After the tweak, awaiting second LGTM before merging.

2021-09-22 17:25 UTC, gmlewis commented on github/event_types.go
> +// BranchProtectionEvent triggered when a check suite is "created", "edited", or "deleted".
```suggestion
// BranchProtectionRuleEvent triggered when a check suite is "created", "edited", or "deleted".
```

2021-09-22 18:03 UTC, gmlewis approved these changes
Thank you, @bhogatemadhura !
LGTM.

Awaiting second LGTM before merging.

2021-09-23 00:24 UTC, bhogatemadhura commented
@wesleimp : can I get your consent too ? :)

2021-09-23 15:46 UTC, bhogatemadhura commented
@gmlewis : How long do we wait to get the second approval ?

2021-09-23 16:07 UTC, gmlewis commented
> @gmlewis : How long do we wait to get the second approval ?

However long it takes, since this repo is maintained by volunteers. 😁

However, if there is an urgent need, I've found that @Parker77 has been incredibly responsive and may be able to help.

2021-09-23 16:30 UTC, bhogatemadhura commented
Thank you @gmlewis.Unforutnately, I need this fix soon. Hoping @Parker77 helps out :)

2021-09-23 16:31 UTC, Parker77 approved these changes
LGTM!

2021-09-23 16:38 UTC, gmlewis commented
> LGTM!

Thank you, @Parker77 !
Merging.

2021-09-23 16:39 UTC, merged

2021-09-23 16:46 UTC, gmlewis commented
@bhogatemadhura - https://github.com/google/go-github/releases/tag/v39.1.0 now contains this change.