Upload Code Scanning Sarif results to GitHub
google/go-github pull request #2165
Opened 2021-10-28 20:21 UTC by ganeshkumarsv

Add a method to upload Code Scanning Sarif results to GitHub

2021-10-30 11:16 UTC, ganeshkumarsv commented on github/code-scanning_test.go
> +		if !reflect.DeepEqual(v, want) {
Thanks for the review. changed to `cmp`

2021-10-30 16:17 UTC, gmlewis requested changes
Thank you, @ganeshkumarsv , but as written, this code is not going to work.

Once you have addressed all my comments, please actually test out your code using the GitHub API and verify that it works correctly.

2021-10-30 16:17 UTC, gmlewis commented on github/code-scanning.go
> +
Please delete this blank line so that the auto-generated Go docs get associated correctly with the struct.

2021-10-30 16:17 UTC, gmlewis commented on github/code-scanning.go
> +// AnalysisResults specifies the results of a code scanning job.
Let's please change the name of this to `SarifAnalysis` and add the 3 missing fields found in the documentation pointed to on line 124:

* `checkout_uri`
* `started_at`
* `tool_name`

The, let's please move this entire struct down to right before the new `UploadSarif` method and also use it as one of the parameters for uploading the analysis results.

2021-10-30 16:17 UTC, gmlewis commented on github/code-scanning.go
> +func (s *CodeScanningService) UploadSarif(ctx context.Context, owner, repo string, commitSHA string, ref string, sarif string) (*Response, error) {
As discussed above, let's change this to:

```suggestion
func (s *CodeScanningService) UploadSarif(ctx context.Context, owner, repo string, sarif *SarifAnalysis) (*SarifID, *Response, error) {
```

Obviously, you will need to make a new `SarifID` struct to return the data that is documented in the GitHub v3 API docs URL above.

2021-10-30 16:17 UTC, gmlewis commented on github/code-scanning.go
> +// For the parameter sarif, you must first compress your SARIF file using gzip and then translate the contents of the file into a Base64 encoding string
```suggestion
// For the parameter sarif, you must first compress your SARIF file using gzip and then translate the contents of the file into a Base64 encoding string.
```

2021-10-30 16:17 UTC, gmlewis commented on github/code-scanning.go
> +	req, err := s.client.NewRequest("POST", u, results)
Please add a blank line before this line for consistency with the rest of the repo.

2021-10-30 16:17 UTC, gmlewis commented on github/code-scanning.go
> +	analysis := new(AnalysisResults)
Please add a blank line before this line for consistency with the rest of the repo.

Also, this is not correct... the `AnalysisResults` struct is not being passed back in the response.  Please re-read the documentation and create a new `SarifID` struct that has the `id` and `url` fields in it and return that instead.

2021-10-30 16:17 UTC, gmlewis commented on github/code-scanning_test.go
> +	const methodName = "UploadSarif"
Please add a blank line before this line for consistency with the rest of this repo.

2021-11-02 16:36 UTC, gmlewis requested changes

2021-11-02 16:36 UTC, gmlewis commented on github/code-scanning.go
> +type SarifID struct {
Please add a godoc-style comment to describe this new struct.

2021-11-02 16:36 UTC, gmlewis commented on github/code-scanning.go
> +	StartedAt   *string `json:"started_at,omitempty"`
```suggestion
	StartedAt   *Timestamp `json:"started_at,omitempty"`
```

2021-11-02 16:36 UTC, gmlewis commented on github/code-scanning_test.go
> +	const methodName = "UploadSarif"
Please add a blank line before this line (79) for consistency with the rest of this repo.

2021-11-02 17:35 UTC, ganeshkumarsv commented
@gmlewis Thanks for all the review comments! I think I addressed all of them and tested. Please let me know if anything else needs to be changed.

2021-11-02 20:52 UTC, gmlewis requested changes

2021-11-02 20:52 UTC, gmlewis commented on github/code-scanning.go
> +// SarifID specifies the status of sarif upload.
```suggestion
// SarifID identifies a sarif analysis upload.
```

2021-11-02 20:52 UTC, gmlewis commented on github/code-scanning_test.go
> +	const methodName = "UploadSarif"
This comment has not yet been addressed.

2021-11-03 01:21 UTC, ganeshkumarsv commented
addressed the remaining comments.

2021-11-03 13:42 UTC, gmlewis approved these changes
Thank you, @ganeshkumarsv !
LGTM.

Awaiting second LGTM (from any other go-github contributor) before merging.

2021-11-05 15:38 UTC, ganeshkumarsv commented
@wesleimp @gmlewis 
gentle bump on the PR 🙏

2021-11-08 07:17 UTC, viveknathani approved these changes

2021-11-08 07:19 UTC, viveknathani commented
> 
> 
> Thank you, @ganeshkumarsv ! LGTM.
> 
> Awaiting second LGTM (from any other go-github contributor) before merging.

LGTM!

2021-11-08 12:21 UTC, gmlewis commented
Thank you, @viveknathani !
Merging.

2021-11-08 12:22 UTC, merged

2021-11-08 12:55 UTC, ganeshkumarsv commented
@gmlewis can we have a new release for go-github? 🙇‍♂️

2021-11-08 12:57 UTC, gmlewis commented
> @gmlewis can we have a new release for go-github? 🙇‍♂️

Yes, I'll work on that today.

2021-11-08 12:58 UTC, ganeshkumarsv commented
Thank you! 😊 🙇‍♂️

2021-11-08 13:26 UTC, gmlewis commented
@ganeshkumarsv - this has been released into `v40`: https://github.com/google/go-github/releases/tag/v40.0.0