test marshal added for trafficbreakdownOptions struct
google/go-github pull request #2190
Opened 2021-10-31 17:16 UTC by sushmitaw

Hi creator,
Added test cases for JSON Resources :
**trafficbreakdownOptions**
Helps: #55 

I have followed all the guidelines to contribute in this repository.
Please revert in case of any changes needed.
I am first time contributor , It will be great help if u can encourage me & accept my contribution.

2021-10-31 17:27 UTC, sushmitaw commented
@andygrunwald pls accept my PR for Hackoctober fest contribution.

2021-10-31 17:29 UTC, andygrunwald commented
@sushmitaw I am honored that you think I am a maintainer of go-github, but I am not. @gmlewis might be able to help you here.

Additionally: go-github is not part of the hacktoberfest efforts. How do I know it? It doesn't have the hactoberfest topic assigned to the repo. Hacktoberfest is opt-in.

2021-10-31 17:32 UTC, sushmitaw commented
@gmlewis pls accept my PR for Hackoctober fest contribution.

2021-11-01 02:36 UTC, gmlewis requested changes

2021-11-01 02:36 UTC, gmlewis commented on github/repos_traffic_test.go
> +		Per: v.String(),
Since this is just a simple string, let's please get rid of line 315 above and replace this with:

```suggestion
		Per: "day",
```

2022-11-03 14:52 UTC, closed without merging