Add new method, RemoveMilesone on IssuesService
google/go-github pull request #2195
Opened 2021-11-02 18:07 UTC by AGMETEOR

Fixes #236

2021-11-02 18:08 UTC, AGMETEOR commented
Hi @gmlewis and @cpanato . Mind taking a look at my PR?

2021-11-02 20:48 UTC, gmlewis requested changes
Thank you, @AGMETEOR !
Just a couple minor tweaks, please, then we'll be ready for a second LGTM before merging.

2021-11-02 20:48 UTC, gmlewis commented on github/issues.go
> +	u := fmt.Sprintf("repos/%v/%v/issues/%d", owner, repo, issueNumber)
```suggestion
	u := fmt.Sprintf("repos/%v/%v/issues/%v", owner, repo, issueNumber)
```

2021-11-02 20:48 UTC, gmlewis commented on github/issues.go
> +		Milestone interface{} `json:"milestone"`
```suggestion
		Milestone *Milestone `json:"milestone"`
```

2021-11-02 20:48 UTC, gmlewis commented on github/issues.go
> +// Remove a milestone from an issue
```suggestion
// Remove a milestone from an issue.
//
// This is a helper method to explicitly update an issue with a `null` milestone, thereby removing it.
//
// GitHub API docs: https://docs.github.com/en/free-pro-team@latest/rest/reference/issues/#update-an-issue
```

2021-11-03 08:21 UTC, cpanato reviewed
i'm not a maintainer of this project, but Glenn already did a great job reviewing this pr

besides that LGTM after the comments being addressed 

thanks for working on this!

2021-11-03 19:21 UTC, AGMETEOR commented
Hi @gmlewis . I have made updates. Kindly requesting for another review.

2021-11-03 19:29 UTC, gmlewis requested changes

2021-11-03 19:34 UTC, AGMETEOR commented on github/issues.go
> +func (s *IssuesService) RemoveMilestone(ctx context.Context, owner string, repo string, issueNumber int) (*Issue, *Response, error) {
Committed the suggestion

2021-11-04 00:18 UTC, gmlewis approved these changes
Thank you, @AGMETEOR !
LGTM.

Merging based upon @cpanato additional approval. 
Thank you, @cpanato !

2021-11-04 00:18 UTC, merged

2021-11-04 07:55 UTC, cpanato commented
/lgtm