Add function to delete a workflow run by ID
google/go-github pull request #2207
Opened 2021-11-22 10:45 UTC by xabi93

This Pull request Adds a new function to delete workflows run from workflow history. The same functionality as this button:
<img width="960" alt="Screenshot 2021-11-22 at 11 43 41" src="https://user-images.githubusercontent.com/6052966/142847721-070de07c-60be-4b84-a8e3-965a43b59246.png">

I cannot reference the documentation in the function comment because is missing the endpoint in the docs

2021-11-22 12:29 UTC, gmlewis requested changes
Thank you, @xabi93 !
Just one tweak, please, then we will be ready for a second LGTM before merging.

2021-11-22 12:29 UTC, gmlewis commented on github/actions_workflow_runs.go
> +// DeleteWorkflowRunLogs deletes a workflow run by ID.
```suggestion
// DeleteWorkflowRun deletes a workflow run by ID.
//
// GitHub API docs: https://docs.github.com/en/rest/reference/actions#delete-a-workflow-run
```

2021-11-22 13:14 UTC, xabi93 commented
@gmlewis done!! 😅

2021-11-22 14:56 UTC, gmlewis approved these changes
Thank you, @xabi93 !
LGTM.

Awaiting second LGTM/Approval from any other contributor to this repo (we don't have to wait for anyone in particular... all contributors are welcome to participate).

2021-11-25 22:30 UTC, wesleimp approved these changes
LGTM 👌🏼

2021-11-26 03:07 UTC, gmlewis commented
Thank you, @wesleimp !
Merging.

2021-11-26 03:08 UTC, merged