Add support External Groups
google/go-github pull request #2217
Opened 2021-12-05 16:07 UTC by kabesan

#2213 
https://docs.github.com/en/enterprise-cloud@latest/rest/reference/teams#external-groups

2021-12-05 17:03 UTC, gmlewis requested changes
Thank you, @kabesan !
Just a few tweaks, please, then we should be ready for a second LGTM before merging.

2021-12-05 17:03 UTC, gmlewis commented on github/teams.go
> +// RemoveConnectedExternalGroup removes the connection between on external group and a team
```suggestion
// RemoveConnectedExternalGroup removes the connection between an external group and a team.
```

2021-12-05 17:03 UTC, gmlewis commented on github/teams_test.go
> +	testNewRequestAndDoFailure(t, methodName, client, func() (*Response, error) {
Please add a blank line before this test.

2021-12-05 17:03 UTC, gmlewis commented on github/teams_test.go
> +	testNewRequestAndDoFailure(t, methodName, client, func() (*Response, error) {
Please add a blank line before this test.

2021-12-05 17:03 UTC, gmlewis commented on github/teams_test.go
> +	testNewRequestAndDoFailure(t, methodName, client, func() (*Response, error) {
Please add a blank line before this test.

2021-12-05 17:03 UTC, gmlewis commented on github/teams_test.go
> +	testNewRequestAndDoFailure(t, methodName, client, func() (*Response, error) {
Please add a blank line before this test.

2021-12-05 17:05 UTC, gmlewis commented
Also, please make sure to run unit tests before pushing (not force-pushing) your upcoming changes.
We squash and merge, so don't worry about the number of commits.
And finally, make sure to run `go generate ./...` and push those changes.
See our CONTRIBUTING.md file for more details.

2021-12-06 07:26 UTC, kabesan commented
@gmlewis Thank your review.
I fiexed, Please re-review.

2021-12-06 14:10 UTC, gmlewis requested changes

2021-12-06 14:10 UTC, gmlewis commented on github/teams_test.go
> +	updatedAt, _ := time.Parse(time.RFC3339, "2021-01-24T11:31:04-06:00")
Here, and everywhere else you use `time.Parse`, please change this to use the already-existing `referenceTime` value created in: `github/timestamp_test.go`.

2021-12-06 14:10 UTC, gmlewis commented on github/teams.go
> +	UpdatedAt *Timestamp                `json:"updated_at,omitempty"`
Please run this file through `go fmt` to fix the indentation.

2021-12-06 15:23 UTC, gmlewis approved these changes
Thank you, @kabesan !
LGTM.

Awaiting second LGTM before merging.

(Please note that ALL other contributors to this repo are welcome to provide the second PR review/comment/approval that we need for merging and that we are not waiting for any particular reviewer unless otherwise noted.)

2021-12-07 15:53 UTC, kabesan commented
Fixed for diff coverage!

2021-12-07 18:37 UTC, gmlewis approved these changes

2021-12-12 15:56 UTC, kabesan commented
@gmlewis Hi
Is second reviewer not active?
Can you add other reviewers?

2021-12-12 16:12 UTC, gmlewis commented
> @gmlewis Hi Is second reviewer not active? Can you add other reviewers?

I am no longer able to add other reviewers, but any other contributor to this repo is welcome to review.

2021-12-17 13:24 UTC, kabesan commented
Hi @pierce-m
Can you review this PR?
I'm waiting for second review.

2021-12-22 22:16 UTC, pierce-m commented
@kabesan Yeah I'll take a look, but probably won't be able to until after the winter holidays

2021-12-22 22:40 UTC, pierce-m approved these changes

2021-12-23 02:32 UTC, gmlewis commented
Thank you, @pierce-m !
Merging.

2021-12-23 02:33 UTC, merged