App hook deliveries API
google/go-github pull request #2226
Opened 2021-12-13 20:46 UTC by pierce-m

Resolves #2225

2021-12-13 21:09 UTC, pierce-m commented
Can we re-run the cla job? I signed it but it hasn't updated 🤔

2021-12-13 21:10 UTC, gmlewis commented
@googlebot - recheck

2021-12-13 21:16 UTC, gmlewis requested changes
Thank you, @pierce-m !
Just a few tweaks, please, then we should be ready for a second LGTM before merging.

Also, could you please send a message to @googlebot like "Hey @googlebot - I signed it." and let's see if it responds.  Thanks again!

2021-12-13 21:16 UTC, gmlewis commented on github/apps_hooks_deliveries.go
> +// ListHookDeliveries lists deliveries of an App webhook
```suggestion
// ListHookDeliveries lists deliveries of an App webhook.
```

2021-12-13 21:16 UTC, gmlewis commented on github/apps_hooks_deliveries.go
> +// GetHookDelivery returns the App webhook delivery with the specified ID
```suggestion
// GetHookDelivery returns the App webhook delivery with the specified ID.
```

2021-12-13 21:16 UTC, gmlewis commented on github/apps_hooks_deliveries.go
> +// RedeliverHookDelivery redelivers a delivery for an App webhook
```suggestion
// RedeliverHookDelivery redelivers a delivery for an App webhook.
```

2021-12-13 21:16 UTC, gmlewis commented on github/apps_hooks_deliveries_test.go
> +package github
```suggestion
// Copyright 2021 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package github
```

2021-12-13 21:31 UTC, gmlewis approved these changes
Thank you, @pierce-m !
LGTM.

Awaiting second LGTM from any other contributor to this repo before merging.

2021-12-16 17:19 UTC, pierce-m commented
@wesleimp can I get some 👀 on this one please?

2021-12-16 17:51 UTC, gmlewis commented
@Parker77 - do you have time to take a look at this one?

2021-12-16 17:52 UTC, Parker77 approved these changes
LGTM.

2021-12-16 17:52 UTC, gmlewis commented
> LGTM.

Thank you, @Parker77!
Merging.

2021-12-16 17:53 UTC, merged