Add support for the pull request review thread event
google/go-github pull request #2326
Opened 2022-03-30 20:05 UTC by taisph

Fixes #2324

2022-03-30 20:14 UTC, gmlewis requested changes

2022-03-30 20:14 UTC, gmlewis commented on github/pulls_threads.go
> +// PullRequestThread represents a ...
Please continue. :smile:

2022-03-30 21:19 UTC, taisph commented
I added the link https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request_review_thread which presumably will be the correct link once they update the docs by looking at the existing structure. I don't know what to expect with regards to when they'll update it as I managed to find [a misnamed issue](https://github.com/github/docs/issues/12295) about the missing documentation that was created back in November 2021.

 Should this PR be kept back until the docs are updated?

2022-03-30 21:28 UTC, gmlewis commented
> Should this PR be kept back until the docs are updated?

I don't think that's necessary.  Many endpoints have been added in the based just based on observing the response received, so I think this is fine. It can always be updated once the official docs are released. Thank you, @taisph !

2022-03-31 18:33 UTC, gmlewis approved these changes
Thank you, @taisph !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2022-04-03 16:13 UTC, raynigon approved these changes
LGTM

2022-04-03 16:45 UTC, gmlewis commented
Thank you, @raynigon !
Merging.

2022-04-03 16:45 UTC, merged