Rerequest Check Run
google/go-github pull request #2358
Opened 2022-05-04 17:41 UTC by leonpham0

Closes out https://github.com/google/go-github/issues/2357

Adds support for https://docs.github.com/en/rest/checks/runs#rerequest-a-check-run

2022-05-04 21:07 UTC, gmlewis requested changes
Thank you, @leonpham0 !
Just one minor tweak, please, then we should be ready for a second LGTM+Approval before merging.

2022-05-04 21:07 UTC, gmlewis commented on github/checks.go
> +	return resp, err
```suggestion
	return s.client.Do(ctx, req, nil)
```

2022-05-04 23:17 UTC, gmlewis approved these changes
Thank you, @leonpham0 !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2022-05-16 12:16 UTC, raynigon approved these changes
LGTM

2022-05-16 14:20 UTC, gmlewis commented
> LGTM

Thank you, @raynigon !
Merging.

2022-05-16 14:20 UTC, merged