Add tag protection
google/go-github pull request #2424
Opened 2022-07-28 20:05 UTC by jfengupgrade

2022-07-28 20:25 UTC, gmlewis requested changes
Thank you, @jfengupgrade !
Just a few tweaks, please.

2022-07-28 20:25 UTC, gmlewis commented on example/tagprotection/main.go
> +// prompts the user for GitHub owner, repo, tag protection pattern and token
```suggestion
// prompts the user for GitHub owner, repo, tag protection pattern and token,
```

2022-07-28 20:25 UTC, gmlewis commented on example/tagprotection/main.go
> +// it will create new tag protection if the user enter pattern in prompt
```suggestion
// then creates a new tag protection if the user entered a pattern at the prompt.
```

2022-07-28 20:25 UTC, gmlewis commented on example/tagprotection/main.go
> +// otherwise it will just list all existing tag protection
```suggestion
// Otherwise, it will just list all existing tag protections.
```

2022-07-28 20:25 UTC, gmlewis commented on example/tagprotection/main.go
> +		tagProtection, _, err := client.Repositories.CreateTagProtection(context.Background(), owner, repo, pattern)
```suggestion
		tagProtection, _, err := client.Repositories.CreateTagProtection(ctx, owner, repo, pattern)
```

2022-07-28 20:25 UTC, gmlewis commented on example/tagprotection/main.go
> +	tagProtections, _, err := client.Repositories.ListTagProtection(context.Background(), owner, repo)
```suggestion
	tagProtections, _, err := client.Repositories.ListTagProtection(ctx, owner, repo)
```

2022-07-28 20:25 UTC, gmlewis commented on example/tagprotection/main.go
> +			return
Instead of `fmt.Printf()... return`, let's please just delete the return and use `log.Fatalf` instead.  
Here, and below.

2022-07-28 20:25 UTC, gmlewis commented on example/tagprotection/main.go
> +		return
Here too.

2022-07-28 20:25 UTC, gmlewis commented on github/repos_tags.go
> +// TagProtectionRequest represents a request to create tag protection
```suggestion
// tagProtectionRequest represents a request to create tag protection.
```

2022-07-28 20:25 UTC, gmlewis commented on github/repos_tags.go
> +type TagProtectionRequest struct {
Let's unexport this struct since it is only used internally.

```suggestion
type tagProtectionRequest struct {
```

2022-07-28 20:25 UTC, gmlewis commented on github/repos_tags.go
> +func (s *RepositoriesService) DeleteTagProtection(ctx context.Context, owner, repo string, tag_protection_id int64) (*Response, error) {
```suggestion
func (s *RepositoriesService) DeleteTagProtection(ctx context.Context, owner, repo string, tagProtectionID int64) (*Response, error) {
```

2022-07-28 22:59 UTC, gmlewis approved these changes
Thank you, @jfengupgrade !
LGTM.

Awaiting second LGTM from any other contributor to this repo before merging.

2022-07-28 23:01 UTC, jfengupgrade commented
@gmlewis Thanks a lot for the reviewing

2022-08-13 21:48 UTC, raynigon approved these changes
LGTM

2022-08-13 22:15 UTC, gmlewis commented
Thank you, @raynigon !
Merging.

2022-08-13 22:15 UTC, merged