Add LFS control
google/go-github pull request #2429
Opened 2022-08-02 02:44 UTC by dsm-kb

Add ability to turn LFS on / off for repo

2022-08-02 23:44 UTC, gmlewis requested changes
Thank you, @dsm-kb !
Just a few minor tweaks, please, then we should be ready for a second LGTM before merging.

2022-08-02 23:44 UTC, gmlewis commented on github/repos_lfs.go
> +// Copyright 2013 The go-github AUTHORS. All rights reserved.
For new files, we give them the year that they are created.

```suggestion
// Copyright 2022 The go-github AUTHORS. All rights reserved.
```

2022-08-02 23:44 UTC, gmlewis commented on github/repos_lfs_test.go
> +// Copyright 2013 The go-github AUTHORS. All rights reserved.
```suggestion
// Copyright 2022 The go-github AUTHORS. All rights reserved.
```

2022-08-02 23:44 UTC, gmlewis commented on github/repos_lfs.go
> +// EnableLfs turns the LFS feature ON for selected repo.
```suggestion
// EnableLFS turns the LFS (Large File Storage) feature ON for the selected repo.
```

2022-08-02 23:44 UTC, gmlewis commented on github/repos_lfs.go
> +func (s *RepositoriesService) EnableLfs(ctx context.Context, owner string, repo string) (*Response, error) {
```suggestion
func (s *RepositoriesService) EnableLFS(ctx context.Context, owner, repo string) (*Response, error) {
```

2022-08-02 23:44 UTC, gmlewis commented on github/repos_lfs.go
> +// DisableLfs turns the LFS feature OFF for selected repo.
```suggestion
// DisableLFS turns the LFS (Large File Storage) feature OFF for the selected repo.
```

2022-08-02 23:44 UTC, gmlewis commented on github/repos_lfs.go
> +func (s *RepositoriesService) DisableLfs(ctx context.Context, owner string, repo string) (*Response, error) {
```suggestion
func (s *RepositoriesService) DisableLFS(ctx context.Context, owner, repo string) (*Response, error) {
```

2022-08-02 23:44 UTC, gmlewis commented on github/repos_lfs_test.go
> +	const methodName = "EnableLfs"
```suggestion
	const methodName = "EnableLFS"
```

2022-08-02 23:44 UTC, gmlewis commented on github/repos_lfs_test.go
> +	const methodName = "DisableLfs"
```suggestion
	const methodName = "DisableLFS"
```

2022-08-03 01:40 UTC, gmlewis requested changes
Sorry I missed a couple minor nits.

2022-08-03 01:40 UTC, gmlewis commented on github/repos_lfs.go
> +// DisableLFS turns the LFS (Large File Storage) feature OFF for the selected repo
```suggestion
// DisableLFS turns the LFS (Large File Storage) feature OFF for the selected repo.
```

2022-08-03 01:40 UTC, gmlewis commented on github/repos_lfs.go
> +// Github API docs: https://docs.github.com/en/rest/repos/lfs#disable-git-lfs-for-a-repository
```suggestion
// GitHub API docs: https://docs.github.com/en/rest/repos/lfs#disable-git-lfs-for-a-repository
```

2022-08-03 12:10 UTC, gmlewis approved these changes
Thank you, @dsm-kb !
LGTM.

Awaiting second LGTM from any other contributor to this repo before merging.

2022-08-03 19:46 UTC, dsm-kb commented
Thank you @gmlewis for the LGTM :-)

2022-08-13 21:27 UTC, raynigon approved these changes
LGTM

@dsm-kb For ypur next PR it would be nice, if you could explain what you want to do in the PR description. Makes the review a bit easier :)

2022-08-13 21:32 UTC, merged

2022-08-13 21:33 UTC, gmlewis commented
Thank you, @raynigon !
Merged.