Add BypassPullRequestAllowances field
google/go-github pull request #2432
Opened 2022-08-04 08:06 UTC by Starttoaster

Closes https://github.com/google/go-github/issues/2431

2022-08-04 11:42 UTC, gmlewis requested changes
Thank you, @Starttoaster !
Just a few minor changes, please.

2022-08-04 11:42 UTC, gmlewis commented on github/repos.go
> +	// The list of user slugs allowed to bypass pull request requirements.
```suggestion
	// The list of users allowed to bypass pull request requirements.
```

2022-08-04 11:42 UTC, gmlewis commented on github/repos.go
> +	// The list of team slugs allowed to bypass pull request requirements.
```suggestion
	// The list of teams allowed to bypass pull request requirements.
```

2022-08-04 11:42 UTC, gmlewis commented on github/repos.go
> +	// The list of app slugs allowed to bypass pull request requirements.
```suggestion
	// The list of apps allowed to bypass pull request requirements.
```

2022-08-04 17:12 UTC, Starttoaster commented
Thanks for the review @gmlewis ! Committed all suggestions.

2022-08-04 17:55 UTC, gmlewis approved these changes
Thank you, @Starttoaster !
LGTM.

Awaiting second LGTM from any other contributor to this repo before merging.

2022-08-04 18:12 UTC, Starttoaster commented
> Thank you, @Starttoaster ! LGTM.
> 
> Awaiting second LGTM from any other contributor to this repo before merging.

Thanks!

2022-08-04 18:48 UTC, gmlewis commented
Whups, I jumped the gun... it looks like some of your contributed files need to be run through `gofmt`, please.

2022-08-04 21:34 UTC, Starttoaster commented
> Whups, I jumped the gun... it looks like some of your contributed files need to be run through `gofmt`, please.

Weird. Usually my text editor fmts for me, I guess it didn't because of the length of the file. Thanks!

2022-08-07 18:55 UTC, Starttoaster commented
@gmlewis pardon me if this comes off as hasty, I just kind of want to switch my go.mods off of my fork, and open up this PR to see if it's merged once a day or so. I was curious what the usual expectation is for duration of time between first and second tier of PR reviews? Not trying to put pressure, I just want to set my expectations accordingly.

2022-08-07 20:43 UTC, gmlewis commented
> @gmlewis pardon me if this comes off as hasty, I just kind of want to switch my go.mods off of my fork, and open up this PR to see if it's merged once a day or so. I was curious what the usual expectation is for duration of time between first and second tier of PR reviews? Not trying to put pressure, I just want to set my expectations accordingly.

Hi @Starttoaster - this repo is maintained by volunteers and we rely on other contributors to the repo to perform second code reviews when appropriate. Sometimes it is immediate, but more often it takes days or weeks. There are a few people that I can reach out to when there is some kind of urgency, but I prefer to not bother them unless there is. However, let's see if anyone steps up by tomorrow and if not, I can request that one of these trustworthy individuals take a look if they have time.

Thank you for your patience.

2022-08-07 21:49 UTC, Starttoaster commented
It's not urgent or anything. No need to disrupt people. I can just keep my go.mods pinned to my fork for eternity if need be, it's just not really my preference is all. I was mostly just interested to hear how this process is intended to go. I enjoy the idea of community PR reviews, but in practice, it's been my observation that it's not usually a great experience for would-be contributors awaiting reviewers because most devs put their focus on their day jobs and then log out at the end of the day to spend time with their families (understandably, because that's how they make money to live.)

Anyway, tl;dr -- no need to move mountains for me. Just wanted to set my expectations correctly so I wouldn't feel compelled to load this PR page every morning.

2022-08-13 21:24 UTC, raynigon approved these changes
LGTM

2022-08-13 21:27 UTC, gmlewis commented
Thank you, @raynigon !
Merging.

2022-08-13 21:28 UTC, merged