feature: adding api and web to meta api endpoint.
google/go-github pull request #2435
Opened 2022-08-17 14:46 UTC by Jamian

The Api and Web lists are returned from the `meta` API but still aren't supported in the Go library. This change exposes them in the same way as the other blocks which are returned. I'm working on a change in the GitHub Terraform provider to also support exposing these API/Web CIDRs so if this is all ok I can continue on with that change as well.

2022-08-17 14:50 UTC, gmlewis requested changes
Thank you, @Jamian !
Just a couple minor tweaks, please, in addition to the CLA.

2022-08-17 14:50 UTC, gmlewis commented on github/misc.go
> +	// which serve GitHub apis.
```suggestion
	// which serve GitHub APIs.
```

2022-08-17 14:50 UTC, gmlewis commented on github/misc.go
> +	Api []string `json:"api,omitempty"`
```suggestion
	API []string `json:"api,omitempty"`
```

2022-08-17 16:10 UTC, Jamian commented
@gmlewis Hey, thanks for the feedback. I have made the changes and sorted the CLA out. 👍

2022-08-17 16:12 UTC, gmlewis commented
Thanks, @Jamian !  I think the tests might need updating, please.

2022-08-18 08:19 UTC, Jamian commented
Hey @gmlewis, of course - awkwardly embarrassing! Just pushed the fixes to get tests passing 🤞

2022-08-18 12:19 UTC, gmlewis approved these changes
Thank you, @Jamian !
LGTM.
Merging.

2022-08-18 12:20 UTC, merged