List Secret Scan Alerts with index based pagination
google/go-github pull request #2446
Opened 2022-08-25 20:35 UTC by AbbanMustafa

2022-08-30 14:20 UTC, gmlewis commented
Thank you, @AbbanMustafa - were you ever able to test this successfully?

2022-09-01 17:04 UTC, AbbanMustafa commented
> Thank you, @AbbanMustafa - were you ever able to test this successfully?

Yes! I verified works for both list option types

2022-09-01 17:23 UTC, gmlewis requested changes
Could you please add a unit test demonstrating how/where/why this is being used?

2022-09-01 19:28 UTC, gmlewis commented
@AbbanMustafa - it looks like some unit tests broke - could you please fix them?  Also make sure your code is formatted... I haven't taken a look yet... just reporting the breakage.

2022-09-01 20:39 UTC, gmlewis commented on github/secret_scanning.go
> +	// Whereas on Enterprise Server, it is just by pagination by index https://docs.github.com/en/enterprise-server@3.6/rest/secret-scanning#list-secret-scanning-alerts-for-an-organization
```suggestion
	// List options can vary on the Enterprise type.
	// On Enterprise Cloud, Secret Scan alerts support requesting by page number
	// along with providing a cursor for an "after" param.
	// See: https://docs.github.com/en/enterprise-cloud@latest/rest/secret-scanning#list-secret-scanning-alerts-for-an-organization
	// Whereas on Enterprise Server, pagination is by index.
	// See: https://docs.github.com/en/enterprise-server@3.6/rest/secret-scanning#list-secret-scanning-alerts-for-an-organization
```

2022-09-01 20:56 UTC, gmlewis approved these changes
Thank you, @AbbanMustafa !
LGTM.
Merging.

2022-09-01 20:58 UTC, merged