Escape special characters in ref name for update ref
google/go-github pull request #2454
Opened 2022-09-08 19:09 UTC by shravan1k

Closes #2453 

Most of the functions that deal with refs make sure to escape the special characters within the ref's name. The `UpdateRef` function doesn't seem to call the function that does this substitution of special characters with their encodings. This PR solves this problem and should now successfully patch remote refs if the `GetRef` function says the corresponding ref exists.

2022-09-09 11:53 UTC, gmlewis approved these changes
Thank you, @shravan1k !
Please add a unit test that demonstrates this change in functionality.

2022-09-09 11:54 UTC, gmlewis requested changes
Whups - checked the wrong box.

Thank you, @shravan1k !
Please add a unit test that demonstrates this change in functionality.

2022-09-09 21:58 UTC, gmlewis approved these changes
Beautiful, @shravan1k !  Thank you!
LGTM.

Awaiting second LGTM from any other contributor to this repo before merging.

2022-09-12 12:43 UTC, marcelosousa approved these changes
LGTM 👍

2022-09-12 12:48 UTC, gmlewis commented
Thank you, @marcelosousa !
Merging.

2022-09-12 12:49 UTC, merged