Create custom role APIs
google/go-github pull request #2494
Opened 2022-10-14 06:42 UTC by mohaldu

resolves #2493

2022-10-15 11:55 UTC, gmlewis commented
Hi @mohaldu - please don't use force-push in this repo... we always squash-and-merge anyway, so it is not necessary. See CONTRIBUTING.md for more details.

2022-10-15 12:03 UTC, gmlewis requested changes
Thank you, @mohaldu!
Just a few changes, please, then we should be ready for a second review before merging.

2022-10-15 12:03 UTC, gmlewis commented on github/orgs_custom_roles.go
> +	u := fmt.Sprintf("orgs/%v/custom_roles/%v", org, roleId)
This one is not going to compile. Please run unit tests locally before pushing. See CONTRIBUTING.md for more information.

```suggestion
	u := fmt.Sprintf("orgs/%v/custom_roles/%v", org, roleID)
```

2022-10-15 12:03 UTC, gmlewis commented on github/orgs_custom_roles.go
> +// DeleteCustomRepoRole deletes an existing custom repository role in this organization
```suggestion
// DeleteCustomRepoRole deletes an existing custom repository role in this organization.
```

2022-10-15 12:03 UTC, gmlewis commented on github/orgs_custom_roles.go
> +func (s *OrganizationsService) DeleteCustomRepoRole(ctx context.Context, org string, roleID string) (*Response, error) {
```suggestion
func (s *OrganizationsService) DeleteCustomRepoRole(ctx context.Context, org, roleID string) (*Response, error) {
```

2022-10-15 12:03 UTC, gmlewis commented on github/orgs_custom_roles.go
> +	return resp, err
```suggestion
	return resp, nil
```

2022-10-16 05:24 UTC, mohaldu commented
Hi @gmlewis  thanks for the review, all changes made

2022-10-16 11:40 UTC, gmlewis commented
@mohaldu - please run `go generate ./...` at the top of the repo then push the resulting changes.
See CONTRIBUTING.md for more details.

2022-10-17 01:22 UTC, gmlewis approved these changes
Thank you, @mohaldu !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2022-10-17 15:38 UTC, valbeat approved these changes
LGTM!

2022-10-17 15:46 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2022-10-17 15:47 UTC, merged