Add apps to restriction rules in branch protection
google/go-github pull request #2509
Opened 2022-10-19 11:16 UTC by jporzucek

Fixes https://github.com/google/go-github/issues/2506

2022-10-19 18:57 UTC, gmlewis requested changes
Thank you, @jporzucek .

2022-10-19 18:57 UTC, gmlewis commented on go.mod
> +	golang.org/x/lint v0.0.0-20210508222113-6edffad5e616 // indirect
Please revert all changes to `go.mod` and `go.sum` as they are unrelated to this PR.

2022-10-19 18:57 UTC, gmlewis commented on go.sum
> +golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550/go.mod h1:yigFU9vqHzYiE8UmvKecakEJjdnWj3jj499lnFckfCI=
Please revert all changes to `go.mod` and `go.sum` as they are unrelated to this PR.

2022-10-20 13:26 UTC, gmlewis approved these changes
Thank you, @jporzucek !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2022-10-20 14:54 UTC, raynigon approved these changes
LGTM

2022-10-20 14:57 UTC, merged