Added test cases for JSON resource marshaling
google/go-github pull request #2520
Opened 2022-10-25 08:51 UTC by Harikesh00

Added test cases for `DispatchRequestOptions`, `TransferRequest`, `SignaturesProtectedBranch`, `DismissalRestrictionsRequest` of file `github/repos.go`

contribution to #55

2022-10-25 13:31 UTC, gmlewis requested changes
Thank you, @Harikesh00 !

2022-10-25 13:31 UTC, gmlewis commented on github/repos_test.go
> +		"client_payload":null
Can you simulate a client payload here?

2022-10-25 13:50 UTC, gmlewis commented
@Harikesh00 - do you want Hacktoberfest credit for this one?  If so, please add to the description in future PRs. Thank you!

2022-10-25 16:40 UTC, Harikesh00 commented on github/repos_test.go
> +		"client_payload":null
sure, I'll do & push the changes

2022-10-25 16:42 UTC, Harikesh00 commented
yes @gmlewis. I want this for Hacktoberfest, kindly add the label for same

2022-10-25 17:32 UTC, Harikesh00 commented on github/repos_test.go
> +		"client_payload":null
changes pushed

2022-10-25 18:37 UTC, gmlewis requested changes
Just for consistency sake, could you please add in the whitespace to all the `want` strings that the standard Go `json.MarshalIndent` would add so that all our JSON examples look the same?

2022-10-26 03:00 UTC, Harikesh00 commented
spaces added
plz check

2022-10-26 13:45 UTC, merged