Add test case for JSON resource marshaling
google/go-github pull request #2528
Opened 2022-10-25 19:09 UTC by vaibhavgholap23

Hi creators,
I have added test cases for :
RepoMergeUpstreamResult struct
under Helps: #55 issue

I have followed all the guidelines to contribute to this repository.
Please revert in case of any changes are needed.
I am a first-time contributor to Hackoctober, It will be great if you review & accept my contribution.

2022-10-25 19:15 UTC, gmlewis requested changes
Let's please format the `want` string with included whitespace as if `json.MarshalIndent` was the function that created it, for consistency across the repo.

2022-10-25 19:15 UTC, gmlewis commented on github/repos_merging_test.go
> +		"base_branch":"base_branch"
```suggestion
		"merge_type": "merge_type",
		"base_branch": "base_branch"
```

2022-10-25 19:19 UTC, vaibhavgholap23 commented on github/repos_merging_test.go
> +		"base_branch":"base_branch"
changes pushed

2022-10-26 00:35 UTC, gmlewis approved these changes
Thank you, @vaibhavgholap23 !
LGTM.
Merging.

2022-10-26 00:36 UTC, merged