Add support for Dependabot alert endpoints
google/go-github pull request #2554
Opened 2022-11-01 16:10 UTC by francois2metz

This add support for reading dependabot alerts: https://docs.github.com/en/rest/dependabot/alerts

2022-11-03 15:29 UTC, gmlewis requested changes
Thank you, @francois2metz !

2022-11-03 15:29 UTC, gmlewis commented on github/dependabot_alerts.go
> +func (s *DependabotService) GetRepoAlert(ctx context.Context, owner string, repo string, number int) (*DependabotAlert, *Response, error) {
```suggestion
func (s *DependabotService) GetRepoAlert(ctx context.Context, owner, repo string, number int) (*DependabotAlert, *Response, error) {
```

2022-11-03 15:29 UTC, gmlewis commented on github/dependabot_alerts.go
> +// GetRepoAlert gets a single repository Dependabot alert
```suggestion
// GetRepoAlert gets a single repository Dependabot alert.
```

2022-11-03 15:29 UTC, gmlewis commented on github/dependabot_alerts.go
> +// ListOrgAlerts lists all Dependabot alerts of an organization
```suggestion
// ListOrgAlerts lists all Dependabot alerts of an organization.
```

2022-11-03 15:29 UTC, gmlewis commented on github/dependabot_alerts.go
> +// ListRepoAlerts lists all Dependabot alerts of a repository
```suggestion
// ListRepoAlerts lists all Dependabot alerts of a repository.
```

2022-11-03 15:29 UTC, gmlewis commented on github/dependabot_alerts.go
> +	Direction string `url:"direction,omitempty"`
```suggestion
	State     *string `url:"state,omitempty"`
	Severity  *string `url:"severity,omitempty"`
	Ecosystem *string `url:"ecosystem,omitempty"`
	Package   *string `url:"package,omitempty"`
	Scope     *string `url:"scope,omitempty"`
	Sort      *string `url:"sort,omitempty"`
	Direction *string `url:"direction,omitempty"`
```

2022-11-03 15:29 UTC, gmlewis commented on github/dependabot_alerts.go
> +	FixedAt               *Timestamp                 `json:"fixed_at"`
```suggestion
	Number                *int                        `json:"number,omitempty"`
	State                 *string                     `json:"state,omitempty"`
	Dependency            *Dependency                 `json:"dependency,omitempty"`
	SecurityAdvisory      *DependabotSecurityAdvisory `json:"security_advisory,omitempty"`
	SecurityVulnerability *AdvisoryVulnerability      `json:"security_vulnerability,omitempty"`
	URL                   *string                     `json:"url,omitempty"`
	HtmlURL               *string                     `json:"html_url,omitempty"`
	CreatedAt             *Timestamp                  `json:"created_at,omitempty"`
	UpdatedAt             *Timestamp                  `json:"updated_at,omitempty"`
	DismissedAt           *Timestamp                 `json:"dismissed_at,omitempty"`
	DismissedBy           *User                      `json:"dismissed_by,omitempty"`
	DismissedReason       *string                     `json:"dismissed_reason,omitempty"`
	DismissedComment      *string                     `json:"dismissed_comment,omitempty"`
	FixedAt               *Timestamp                 `json:"fixed_at,omitempty"`
```

2022-11-03 15:29 UTC, gmlewis commented on github/dependabot_alerts.go
> +	WithdrawnAt     *Timestamp              `json:"withdrawn_at"`
```suggestion
	GHSAID          *string                  `json:"ghsa_id,omitempty"`
	CVEID           *string                  `json:"cve_id,omitempty"`
	Summary         *string                  `json:"summary,omitempty"`
	Description     *string                  `json:"description,omitempty"`
	Vulnerabilities []*AdvisoryVulnerability `json:"vulnerabilities,omitempty"`
	Severity        *string                  `json:"severity,omitempty"`
	CVSs            *AdvisoryCvss            `json:"cvss,omitempty"`
	CWEs            []*AdvisoryCwes          `json:"cwes,omitempty"`
	Identifiers     []*AdvisoryIdentifier    `json:"identifiers,omitempty"`
	References      []*AdvisoryReference     `json:"references,omitempty"`
	PublishedAt     *Timestamp               `json:"published_at,omitempty"`
	UpdatedAt       *Timestamp               `json:"updated_at,omitempty"`
	WithdrawnAt     *Timestamp              `json:"withdrawn_at,omitempty"`
```

2022-11-03 15:29 UTC, gmlewis commented on github/dependabot_alerts.go
> +	Name  string `json:"name"`
```suggestion
type AdvisoryCWEs struct {
	CWEID *string `json:"cwe_id,omitempty"`
	Name  *string `json:"name,omitempty"`
```

2022-11-03 15:29 UTC, gmlewis commented on github/dependabot_alerts.go
> +type Dependency struct {
For this struct and all other exported structs, please add a well-formed Godoc-style comment (complete sentence with punctuation) describing the purpose of the struct and what it represents.

2022-11-03 15:29 UTC, gmlewis commented on github/dependabot_alerts.go
> +	Scope        string               `json:"scope"`
```suggestion
	Package      *VulnerabilityPackage `json:"package,omitempty"`
	ManifestPath *string               `json:"manifest_path,omitempty"`
	Scope        *string               `json:"scope,omitempty"`
```

2022-11-03 15:29 UTC, gmlewis commented on github/dependabot_alerts.go
> +	VectorString string  `json:"vector_string"`
```suggestion
	Score        *float64 `json:"score,omitempty"`
	VectorString *string  `json:"vector_string,omitempty"`
```

2022-11-03 15:29 UTC, gmlewis commented on github/github.go
> +	// For paginated result sets, the number of results to include per page starting from the first matching result.
```suggestion
	// For paginated result sets, the number of results per page (max 100), starting from the first matching result.
	// This parameter must not be used in combination with last.
```

2022-11-03 15:29 UTC, gmlewis commented on github/github.go
> +	// For paginated result sets, the number of results to include per page starting from the last matching result.
```suggestion
	// For paginated result sets, the number of results per page (max 100), starting from the last matching result.
	// This parameter must not be used in combination with first.
```

2022-11-03 17:53 UTC, gmlewis commented
@francois2metz - just FYI - no need to force-push to your PRs in this repo because we always squash-merge at the end anyway, and it is easier for reviewers if you don't. See CONTRIBUTING.md for more details. Also, please make sure to run `gofmt` on the modified files and `go generate ./...` before pushing.  Thanks.

2022-11-03 20:18 UTC, gmlewis approved these changes
Thank you, @francois2metz !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2022-11-03 20:19 UTC, gmlewis commented
@francois2metz - please make sure to run `gofmt` and `go generate ./...` and push the results to make the tests pass.

2022-11-03 20:51 UTC, gmlewis approved these changes

2022-11-07 20:45 UTC, valbeat approved these changes

2022-11-07 23:48 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2022-11-07 23:49 UTC, merged