Consume the 'require_last_push_approval' field from the API response
google/go-github pull request #2567
Opened 2022-11-16 13:35 UTC by noamd-legit

2022-11-16 14:03 UTC, gmlewis requested changes
Thank you, @noamd-legit !
Could you please also add this field (but as a `*bool`) to the `PullRequestReviewsEnforcementUpdate` struct?

2022-11-16 15:05 UTC, noamd-legit commented
@gmlewis Added :)

2022-11-16 15:08 UTC, gmlewis requested changes

2022-11-16 15:08 UTC, gmlewis commented on github/repos.go
> +	RequireLastPushApproval *bool `json:"require_last_push_approval"`
```suggestion
	RequireLastPushApproval *bool `json:"require_last_push_approval,omitempty"`
```

2022-11-16 17:26 UTC, gmlewis commented
You will probably also need to run `go generate ./...` as described in CONTRIBUTING.md. Sorry for the short reviews... I'm on Android.

2022-11-17 07:59 UTC, noamd-legit commented
`go generate` doesn't seem to generate diff after syncing with the main branch

2022-11-17 12:56 UTC, gmlewis commented
Did you literally type `go generate ./...` in the top-level directory?
(_Not_ `go generate`.)

2022-11-17 13:58 UTC, gmlewis approved these changes
Thank you, @noamd-legit !
LGTM.
Merging.

2022-11-17 14:01 UTC, merged