Add support for repository actions access level / permission
google/go-github pull request #2578
Opened 2022-11-28 14:14 UTC by s4nji

This PR adds support for the following endpoints and closes #2575:  
[`GET` `/repos/{owner}/{repo}/actions/permissions/access`](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/permissions#get-the-level-of-access-for-workflows-outside-of-the-repository)  
[`PUT` `/repos/{owner}/{repo}/actions/permissions/access`](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/permissions#set-the-level-of-access-for-workflows-outside-of-the-repository)

2022-11-28 14:28 UTC, gmlewis requested changes
Thank you, @s4nji !
Just a couple minor tweaks, please, then we will be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2022-11-28 14:28 UTC, gmlewis commented on github/repos_actions_access.go
> +	return resp, err
```suggestion
	return s.client.Do(ctx, req, nil)
```

2022-11-28 14:28 UTC, gmlewis commented on github/repos_actions_access.go
> +	// Possible values are: "none", "organization" "enterprise"
```suggestion
	// Possible values are: "none", "organization" "enterprise".
```

2022-11-28 14:36 UTC, gmlewis approved these changes
Thank you, @s4nji !
LGTM.
Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2022-12-01 22:41 UTC, valbeat approved these changes
LGTM!

2022-12-01 22:52 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2022-12-01 22:52 UTC, merged