Add support for GitHub Environments for Pro/Teams pricing plans
google/go-github pull request #2611
Opened 2022-12-29 13:41 UTC by AnitaErnszt

The PR fixes the issue reported on https://github.com/google/go-github/issues/2602

In June GitHub made the environments and environment protection rules [generally available](https://github.blog/changelog/2021-06-22-github-actions-environments-environment-protection-rules-and-environment-secrets-are-generally-available/), however, the wait_timer and reviewers remain limited to enterprise.

Code was written to send `wait_timer` and `reviewers` with default values if no value is present, so existing settings can be cleared. 
Due to this, the code was returning 422 when called to create environments for Pro/Team private repos, as these parameters are only supported for enterprise or public repos.

PR intends to handle the error with a retry when the following conditions are met:
- error code is 422
- wait_timer is the default value (0)
- reviewers is the default value ([])

When retrying the call, a new object is sent, which only contains the parameters that are accepted for Pro/Teams private repos.

2022-12-29 13:48 UTC, AnitaErnszt commented
@gmlewis Please kindly check if this implementation makes sense. I have tested the code locally for:
- pro/teams private repos -> successfully creates the environment
- free plan public repos -> successfully creates the environment
- free plan private repos -> 404, which is expected

private enterprise repos should have the same 'route' as the free plan public repos.

Unfortunately, I don't know how to extend the testing function to test the different 'paths'

2022-12-29 14:29 UTC, gmlewis requested changes
Thank you, @AnitaErnszt !

We definitely need to add in tests for the special cases, and it should be relatively simple.
~In a new test, instead of returning a 200 OK, your could would initially return a 422, and then your test would look like all the others and return new responses.~

Alternatively, and maybe this would be the best approach anyway...

Instead of making a huge indented block like we have now, you could make a new method that is _NOT_ exported... something like `createNewEnvNoEnterprise` and then simply call it:

```go
if resp != nil &&  resp.StatusCode == http.StatusUnprocessableEntity && environment != nil && len(environment.Reviewers) == 0 && environment.GetWaitTimer() == 0 {
  return s.createNewEnvNoEnterprise(u, environment)
}
```

Then that way, you can have two new test functions... one just to make sure the 422 triggers the `if` and the other test function can fully test out `createNewEnvNoEnterprise` (like we already do for every other existing endpoint method).  Does that make sense?

2022-12-29 14:29 UTC, gmlewis commented on github/repos_environments.go
> +type CreateUpdateEnvironmentWithoutEnterprise struct {
This should not be exported as it is only used internally.

```suggestion
type createUpdateEnvironmentWithoutEnterprise struct {
```

2022-12-29 14:29 UTC, gmlewis commented on github/repos_environments.go
> +		if resp.StatusCode == 422 && len(environment.Reviewers) == 0 && *environment.WaitTimer == 0 {
```suggestion
		if resp != nil &&  resp.StatusCode == http.StatusUnprocessableEntity && environment != nil && len(environment.Reviewers) == 0 && environment.GetWaitTimer() == 0 {
```

2022-12-30 15:56 UTC, gmlewis requested changes
I know this is in "Draft" state, but wanted to provide some feedback.
Obviously, we need two more test functions to test the added "if" condition and the new method.
Thank you!

2022-12-30 15:56 UTC, gmlewis commented on github/repos_environments.go
> +
Please delete this blank line, as we want to keep the error processing tightly coupled to the line that generates the error.

2022-12-30 15:56 UTC, gmlewis commented on github/repos_environments.go
> +// Currently only the `deployment_branch_policy` paramter is supported for Pro/Team private repos
```suggestion
// createNewEnvNoEnterprise is an internal function for cases where the original call returned 422.
// Currently only the `deployment_branch_policy` parameter is supported for Pro/Team private repos.
```

2022-12-30 15:56 UTC, gmlewis commented on github/repos_environments.go
> +
Please delete this blank line.

2022-12-30 15:56 UTC, gmlewis commented on github/repos_environments.go
> +
Please delete this blank line.

2022-12-30 15:56 UTC, gmlewis commented on github/repos_environments.go
> +
```suggestion
		}
		return nil, resp, err
	}
```

2022-12-30 15:56 UTC, gmlewis commented on github/repos_environments.go
> +// CreateUpdateEnvironmentWithoutEnterprise represents the fields accepted for Pro/Teams private repos.
```suggestion
// createUpdateEnvironmentNoEnterprise represents the fields accepted for Pro/Teams private repos.
```

2023-01-02 17:05 UTC, AnitaErnszt commented
@gmlewis I have added the tests. 
I wasn't sure how to decide what API response to return (422 or 200), so I used a counter for now. I'm open to suggestions

2023-01-02 17:10 UTC, AnitaErnszt commented
On another note the contributor guide is recommending to run `golint` however, this project has been [deprecated](https://github.com/golang/lint)

2023-01-04 03:28 UTC, Xorima approved these changes
LGTM

2023-01-04 04:18 UTC, gmlewis commented
Thank you, @Xorima !
Merging.

2023-01-04 04:18 UTC, merged