new api deployment branch policy endpoint added
google/go-github pull request #2621
Opened 2023-01-09 16:45 UTC by Ismael-Moreno

This PR adds all the endpoints from deployment-branch-policies: https://docs.github.com/en/rest/deployments/branch-policies?apiVersion=2022-11-28#about-deployment-branch-policies

2023-01-10 05:08 UTC, gmlewis requested changes
Thank you, @Ismael-Moreno !
Please make sure to run `gofmt` on your source files.
Also, please make sure to not use force-push for your upcoming commit(s), since we always use squash-and-merge in this repo.  See CONTRIBUTING.md for more info.

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +package github
Please add the standard copyright header (as seen in other files) followed by a blank line to this file and use the year 2023.

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies_test.go
> +package github
Please add the standard copyright header (as seen in other files) followed by a blank line to this file and use the year 2023.

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +type DeploymentBranchPolicy struct {
Please add "godoc"-style comments to each exported struct describing its purpose.

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +func (s *RepositoriesService) ListDeploymentBranchPolicies(ctx context.Context, owner, repo string, environment string) (*DeploymentBranchPolicyResponse, *Response, error) {
```suggestion
func (s *RepositoriesService) ListDeploymentBranchPolicies(ctx context.Context, owner, repo, environment string) (*DeploymentBranchPolicyResponse, *Response, error) {

```

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +	u := fmt.Sprintf("repos/%s/%s/environments/%s/deployment-branch-policies", owner, repo, environment)
Please use `%v` for consistency and ease of searching through code for endpoints.

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +func (s *RepositoriesService) GetDeploymentBranchPolicy(ctx context.Context, owner, repo string, environment string, branchPolicyID int64) (*DeploymentBranchPolicy, *Response, error) {
```suggestion
func (s *RepositoriesService) GetDeploymentBranchPolicy(ctx context.Context, owner, repo, environment string, branchPolicyID int64) (*DeploymentBranchPolicy, *Response, error) {

```

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +	u := fmt.Sprintf("repos/%s/%s/environments/%s/deployment-branch-policies/%d", owner, repo, environment, branchPolicyID)
ditto

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +func (s *RepositoriesService) CreateDeploymentBranchPolicy(ctx context.Context, owner, repo string, environment string, request *DeploymentBranchPolicyRequest) (*DeploymentBranchPolicy, *Response, er
```suggestion
func (s *RepositoriesService) CreateDeploymentBranchPolicy(ctx context.Context, owner, repo, environment string, request *DeploymentBranchPolicyRequest) (*DeploymentBranchPolicy, *Response, error) {

```

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +	u := fmt.Sprintf("repos/%s/%s/environments/%s/deployment-branch-policies", owner, repo, environment)
ditto

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +func (s *RepositoriesService) UpdateDeploymentBranchPolicy(ctx context.Context, owner, repo string, environment string, branchPolicyID int64, request *DeploymentBranchPolicyRequest) (*DeploymentBranc
```suggestion
func (s *RepositoriesService) UpdateDeploymentBranchPolicy(ctx context.Context, owner, repo, environment string, branchPolicyID int64, request *DeploymentBranchPolicyRequest) (*DeploymentBranchPolicy, *Response, error) {

```

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +	u := fmt.Sprintf("repos/%s/%s/environments/%s/deployment-branch-policies/%d", owner, repo, environment, branchPolicyID)
ditto

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +func (s *RepositoriesService) DeleteDeploymentBranchPolicy(ctx context.Context, owner, repo string, environment string, branchPolicyID int64) (*Response, error) {
```suggestion
func (s *RepositoriesService) DeleteDeploymentBranchPolicy(ctx context.Context, owner, repo, environment string, branchPolicyID int64) (*Response, error) {

```

2023-01-10 05:08 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +	u := fmt.Sprintf("repos/%s/%s/environments/%s/deployment-branch-policies/%d", owner, repo, environment, branchPolicyID)
ditto

2023-01-10 12:56 UTC, gmlewis requested changes
Thank you, @jnewland !
One minor nit, please, then we will be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2023-01-10 12:56 UTC, gmlewis commented on github/repos_deployments_branch_policies.go
> +// DeploymentBranchPolicyRequest represents a deployment branch policy request
```suggestion
// DeploymentBranchPolicyRequest represents a deployment branch policy request.
```

2023-01-10 12:58 UTC, gmlewis commented
Also, please make sure all unit tests pass locally before pushing the next commit.

2023-01-10 15:30 UTC, Ismael-Moreno commented
This last one pass the three checks shown in the Contributing guide:
go generate github.com/google/go-github/...
go test github.com/google/go-github/...
go vet github.com/google/go-github/...
Please tell me if there is any other tests I'm missing, thank you for your patience.

2023-01-10 16:35 UTC, gmlewis approved these changes
Thank you, @Ismael-Moreno !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-01-10 17:40 UTC, Parker77 approved these changes
LGTM!

2023-01-10 17:40 UTC, gmlewis commented
Thank you, @Parker77 !
Merging.

2023-01-10 17:43 UTC, gmlewis requested changes
Sorry, @Ismael-Moreno - but as I was about to merge, I noticed that `DeploymentBranchPolicies` is singular `Deployment` whereas the new filenames are `..._deployments_branch_...` .

Could you please rename the new files to use a singular `..._deployment_...` please?

2023-01-11 12:26 UTC, gmlewis approved these changes
Thank you, @Ismael-Moreno !
Merging.

2023-01-11 12:31 UTC, merged