Add RequireLastPushApproval field to UpdateBranchProtection
google/go-github pull request #2629
Opened 2023-01-16 23:26 UTC by liaodaniel

Fixes https://github.com/google/go-github/issues/2628

Signed-off-by: Daniel Liao <10663736+liaodaniel@users.noreply.github.com>

2023-01-16 23:33 UTC, gmlewis requested changes
Thank you, @liaodaniel!
This field is optional, so we need to treat it a bit differently.

2023-01-16 23:33 UTC, gmlewis commented on github/repos.go
> +	RequireLastPushApproval bool `json:"require_last_push_approval"`
```suggestion
	RequireLastPushApproval *bool `json:"require_last_push_approval,omitempty"`
```

2023-01-16 23:51 UTC, liaodaniel commented on github/repos.go
> +	RequireLastPushApproval bool `json:"require_last_push_approval"`
Updated with the suggestion

2023-01-17 01:24 UTC, gmlewis approved these changes
Thank you, @liaodaniel !
LGTM.
Merging.

2023-01-17 01:25 UTC, merged