Add NewTokenClient
google/go-github pull request #2637
Opened 2023-01-20 16:12 UTC by icholy

Fixes #2636

2023-01-20 16:33 UTC, gmlewis requested changes

2023-01-20 16:33 UTC, gmlewis commented on github/github.go
> +// NewClient returns a new GitHub API client authenticated with the provided token.
```suggestion
// NewTokenClient returns a new GitHub API client authenticated with the provided token.
```

2023-01-20 16:33 UTC, gmlewis commented on github/github.go
> +		),
How about collapsing these 7 lines?

```suggestion
		oauth2.NewClient(ctx, oauth2.StaticTokenSource(	&oauth2.Token{AccessToken: token})),
```

2023-01-20 16:45 UTC, icholy commented
I removed the context parameter since I think most users won't be needing it. Let me know if you disagree.

2023-01-20 17:49 UTC, gmlewis approved these changes
Thank you, @icholy !
LGTM.

Awaiting second LGTM+Approval from any other contributor to the repo.

2023-01-25 14:42 UTC, valbeat approved these changes
LGTM!

2023-01-25 15:03 UTC, icholy commented
Should I squash?

2023-01-25 15:07 UTC, gmlewis commented
> Should I squash?

No need to squash, as we always "Squash and Merge" all PRs in this repo.  Thanks, though.

2023-01-25 15:09 UTC, gmlewis commented
Do you want to update an example before merging, @icholy ?

2023-01-25 15:09 UTC, gmlewis commented
> LGTM!

Thank you, @valbeat !

2023-01-25 15:14 UTC, icholy commented
I'll do a separate PR later.

2023-01-25 15:17 UTC, merged