Add DNS health checks support for Github Pages
google/go-github pull request #2746
Opened 2023-04-09 14:25 UTC by oslowalk

Fixes #2745

Allows requesting a DNS health check for the CNAME configured for a repository's GitHub Pages.

2023-04-09 14:54 UTC, gmlewis requested changes
Thank you, @oslowalk !
Just a few minor tweaks, please.

2023-04-09 14:54 UTC, gmlewis commented on github/repos_pages.go
> +// PagesDomain represents a domain associated with a Github Pages site.
```suggestion
// PagesDomain represents a domain associated with a GitHub Pages site.
```

2023-04-09 14:54 UTC, gmlewis commented on github/repos_pages.go
> +	HasCNAMERecordPresent         *bool   `json:"has_cname_record,omitempty"`
```suggestion
	HasCNAMERecord         *bool   `json:"has_cname_record,omitempty"`
```

2023-04-09 14:54 UTC, gmlewis commented on github/repos_pages.go
> +// PagesHealthCheckResponse represents the response given for the health check of a Github Pages site.
```suggestion
// PagesHealthCheckResponse represents the response given for the health check of a GitHub Pages site.
```

2023-04-09 15:17 UTC, gmlewis approved these changes
Thank you, @oslowalk !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-04-12 03:12 UTC, valbeat approved these changes
LGTM!

2023-04-12 12:56 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2023-04-12 12:56 UTC, merged