add workflow run and workflow to deployment event
google/go-github pull request #2755
Opened 2023-04-14 00:08 UTC by soniachikh

2023-04-14 00:33 UTC, gmlewis requested changes
Thank you, @soniachikh .
Please run `go generate ./...` as described in CONTRIBUTING.md and push the results to this PR.

2023-04-14 00:33 UTC, gmlewis commented on github/event_types.go
> -
Let's please leave this blank line as a separator for the next section.

2023-08-15 20:25 UTC, gmlewis requested changes

2023-08-15 20:25 UTC, gmlewis commented on github/event_types.go
> -
See how the blank line moved?  Can you please revert this change?

<img width="1728" alt="line-moved-2023-08-15_16-22-43" src="https://github.com/google/go-github/assets/6598971/e8288b48-a700-44f2-aadd-4f04e8741523">

2023-08-15 20:29 UTC, gmlewis commented
@google-ospo-team - here is another PR where the googlebot has failed to comment.  Please address.

2023-08-15 20:31 UTC, gmlewis approved these changes
Thank you, @soniachikh !
LGTM.

Awaiting response from @google-ospo-team before merging.

2023-08-15 20:32 UTC, gmlewis commented
Ah!  We now have the cla/google check - @soniachikh - please follow the instructions to sign the Google CLA and then we can merge this PR.  Thank you!

2023-08-15 20:40 UTC, merged

2023-08-15 21:41 UTC, google-admin commented
FYI - there is an ongoing issue with GitHub webhooks (https://www.githubstatus.com/) that is likely causing the delays in the CLA check running.

2023-08-16 13:07 UTC, stockmaj commented
@gmlewis is there a plan to release soon?  I see it's been a while.

2023-08-16 15:48 UTC, gmlewis commented
> @gmlewis is there a plan to release soon? I see it's been a while.

Yes, you are right, and we've had a lot of activity in the repo since the last release.  
It would be nice to get #2865 and #2869 reviewed and merged... and maybe even #2876 .
If you could assist by reviewing the outstanding PRs, that would help tremendously.
Thank you!

2023-08-16 18:32 UTC, gmlewis commented
@stockmaj - here is the new release:
https://github.com/google/go-github/releases/tag/v54.0.0

2023-08-16 21:42 UTC, stockmaj commented
Thank you.