Support deployment protection rule event types
google/go-github pull request #2773
Opened 2023-04-27 18:30 UTC by BoyangHuang

This commit adds the deployment_protection_rule event type to the list of parseable event types

2023-04-27 18:53 UTC, gmlewis requested changes
Thank you, @BoyangHuang !
After a few tweaks, we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2023-04-27 18:53 UTC, gmlewis commented on github/event.go
> +	case "DeploymentProtectionRule":
```suggestion
	case "DeploymentProtectionRuleEvent":
```

2023-04-27 18:53 UTC, gmlewis commented on github/event_types.go
> +// DeploymentProtectionRuleEvent represents a deployment protection rule
```suggestion
// DeploymentProtectionRuleEvent represents a deployment protection rule event.
```

2023-04-27 18:53 UTC, gmlewis commented on github/event_types.go
> +// The Webhook even name is "deployment_protection_rule".
```suggestion
// The Webhook event name is "deployment_protection_rule".
```

2023-04-27 18:53 UTC, gmlewis commented on github/event_types.go
> +	PullRequest           *PullRequest  `json:"pull_request,omitempty"`
```suggestion
	PullRequests           []*PullRequest  `json:"pull_requests,omitempty"`
```

2023-04-27 18:53 UTC, gmlewis commented on github/event_types.go
> +
```suggestion
Event *string `json:"event,omitempty"`
```

2023-04-27 18:53 UTC, gmlewis commented on github/messages.go
> +		"deployment_protection_rule":     "DeploymentProtectionRule",
```suggestion
		"deployment_protection_rule":     "DeploymentProtectionRuleEvent",
```

2023-04-27 19:06 UTC, BoyangHuang commented
> Thank you, @BoyangHuang ! After a few tweaks, we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

Thank you for catching my mistakes :) much appreciated

2023-04-27 19:12 UTC, gmlewis commented
Sorry, I forgot to mention that you will need to `gofmt` the files after you add my suggestions. Also make sure to run `go generate ./...` again then push the changes. Thank you!

2023-04-27 19:42 UTC, gmlewis approved these changes
Thank you, @BoyangHuang !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-05-04 23:20 UTC, BoyangHuang commented
small bump here - is there any contributor available to give this a quick look? Thank you!

2023-05-08 16:48 UTC, gmlewis commented
Hi @valbeat - do you have time for a code review?

2023-05-14 06:21 UTC, valbeat approved these changes
LGTM!

2023-05-14 11:36 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2023-05-14 11:36 UTC, merged