Support repository_id in org ruleset conditions
google/go-github pull request #2825
Opened 2023-07-03 11:42 UTC by ysoldak

This PR adds support for referencing repositories by ID in Ruleset conditions.
See https://docs.github.com/en/rest/orgs/rules?apiVersion=2022-11-28#create-an-organization-repository-ruleset

API is changed a bit, probably a low impact since v53.2.0 (with ruleset support added) was released just recently and hopefully not many have code using it in production.

The change `RulesetRepositoryConditionParameters` -> `RulesetRepositoryNamesConditionParameters`

I'm open for suggestions for a change that would not shake the API.

2023-07-04 16:32 UTC, gmlewis requested changes
Thank you, @ysoldak !
Just a few tweaks, please, then we will be ready for a second LGTM+Approval before merging.

2023-07-04 16:32 UTC, gmlewis commented on github/repos_rules.go
> +// Set either RepositoryName or RepositoryId, not both
```suggestion
// Set either RepositoryName or RepositoryID, not both.
```

2023-07-04 16:32 UTC, gmlewis commented on github/repos_rules.go
> +	RepositoryIds []int64 `json:"repository_ids,omitempty"`
```suggestion
// RulesetRepositoryIDsConditionParameters represents the conditions object for repository_ids.
type RulesetRepositoryIDsConditionParameters struct {
	RepositoryIDs []int64 `json:"repository_ids,omitempty"`
```

2023-07-04 16:32 UTC, gmlewis commented on github/repos_rules.go
> +	RepositoryId   *RulesetRepositoryIdsConditionParameters   `json:"repository_id,omitempty"`
```suggestion
	RepositoryID   *RulesetRepositoryIDsConditionParameters   `json:"repository_id,omitempty"`
```

2023-07-04 16:32 UTC, gmlewis commented on github/orgs_rules_test.go
> +func TestOrganizationsService_CreateOrganizationRulesetRepoNames(t *testing.T) {
```suggestion
func TestOrganizationsService_CreateOrganizationRuleset_RepoNames(t *testing.T) {
```

2023-07-04 16:32 UTC, gmlewis commented on github/orgs_rules_test.go
> +func TestOrganizationsService_CreateOrganizationRulesetRepoIds(t *testing.T) {
```suggestion
func TestOrganizationsService_CreateOrganizationRuleset_RepoIDs(t *testing.T) {
```

2023-07-04 19:15 UTC, gmlewis commented
Please also update the unit tests so that `go test ./...` passes on your local machine.

2023-07-04 20:16 UTC, ysoldak commented
🤦 PTAL

2023-07-04 20:33 UTC, gmlewis approved these changes
Thank you, @ysoldak !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-07-05 09:50 UTC, ysoldak commented
Thanks, @gmlewis

I thought worth to reference GitHub's own statement about API change:
https://github.blog/changelog/2023-06-27-repository-rules-public-beta-updates/

The part this PR addresses is "Added a repository picker to target select repositories for organization rulesets."

2023-07-15 06:44 UTC, liaodaniel approved these changes
LGTM

2023-07-15 12:05 UTC, gmlewis commented
Thank you, @liaodaniel !
Merging.

2023-07-15 12:06 UTC, merged