Added support for `personal_access_token_request` webhook event type
google/go-github pull request #2826
Opened 2023-07-04 11:00 UTC by joaopenteado

This PR adds support for the [`personal_access_token_request`](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#personal_access_token_request) webhook event.

> This event occurs when there is activity relating to a request for a fine-grained personal access token to access resources that belong to a resource owner that requires approval for token access.

2023-07-04 17:06 UTC, gmlewis requested changes
Thank you, @joaopenteado !
Just a few tweaks please, then we will be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2023-07-04 17:06 UTC, gmlewis commented on github/event_types.go
> +type PersonalAccessTokenRequest struct {
Please add a godoc-style comment to this new struct.

2023-07-04 17:06 UTC, gmlewis commented on github/event_types.go
> +type PersonalAccessTokenPermissions struct {
Please add a godoc-style comment to this new struct.

2023-07-04 22:51 UTC, joaopenteado commented
Thanks for the very quick response, @gmlewis!
I've just committed the documentation changes requested. Let me know if you want any additional changes.

2023-07-04 23:00 UTC, gmlewis approved these changes
Thank you, @joaopenteado !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-07-06 15:50 UTC, joaopenteado commented
@gmlewis upon further testing, I've actually found that this webhook delivers an map in the API. This isn't very well documented IMO but could be inferred I guess. I've updated the event type to fix this. Here's an excerpt from a webhook event I tested:

```json
{
  "action": "created",
  "personal_access_token_request": {
    "id": 11233,
    "owner": { /* ... */ },
    "repository_selection": "all",
    "repository_count": null,
    "repositories": null,
    "permissions_added": {
      "organization": {
        "organization_announcement_banners": "write",
        "organization_events": "read"
      },
      "repository": {
        "codespaces_lifecycle_admin": "read",
        "metadata": "read",
        "security_events": "write"
      }
    },
    "permissions_upgraded": {},
    "permissions_result": {
      "organization": {
        "organization_announcement_banners": "write",
        "organization_events": "read"
      },
      "repository": {
        "codespaces_lifecycle_admin": "read",
        "metadata": "read",
        "security_events": "write"
      }
    },
    "created_at": "2023-07-07T00:37:57+09:00",
    "token_expired": false,
    "token_expires_at": "2023-08-05T15:37:56Z",
    "token_last_used_at": null
  },
  "organization": { /* ... */ },
  "sender": { /* ... */},
  "installation": {
    "id": 1111111,
    "node_id": "xxxxxxxxxxxxxx"
  }
```

2023-07-06 16:27 UTC, gmlewis approved these changes
Thank you, @joaopenteado !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-07-15 06:35 UTC, liaodaniel approved these changes
LGTM

2023-07-15 12:02 UTC, gmlewis commented
Thank you, @liaodaniel !
Merging.

2023-07-15 12:03 UTC, merged