feat: support for projects_v2 and projects_v2_item webhook events
google/go-github pull request #2868
Opened 2023-08-13 10:53 UTC by nikpivkin

Closes https://github.com/google/go-github/issues/2867

Added support for [projects_v2](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#projects_v2) and [projects_v2_item](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#projects_v2_item) webhook events.

2023-08-13 14:56 UTC, gmlewis commented
This PR has significant conflicts with #2865 due to said PR dramatically changing the internals for webhook events (which will hopefully also reduce the maintenance burden and increase the simplicity of future PRs like this one).

So I apologize for the timing.

We can either move forward with this PR and have more work required in #2865 or we can move forward with #2865 then require changes here.

I'm honestly fine either way.

Do you have a preference @nikpivkin ?
Or do you have a preference, @evankanderson?

2023-08-13 15:06 UTC, evankanderson commented
I'm happy either way; I'll be updating my PR tomorrow probably

2023-08-13 15:28 UTC, gmlewis requested changes
Thank you, @nikpivkin !
Just a few minor tweaks, please before proceeding.

2023-08-13 15:28 UTC, gmlewis commented on github/event_types.go
> +// The Webhook event name is "projects_v2"
nit: Please add punctuation to godoc-style comments.

```suggestion
// The Webhook event name is "projects_v2".
```

2023-08-13 15:28 UTC, gmlewis commented on github/event_types.go
> +// ProjectV2ItemEvent triggered when there is activity relating to an item on an organization-level project.
```suggestion
// ProjectV2ItemEvent is triggered when there is activity relating to an item on an organization-level project.
```

2023-08-13 15:28 UTC, gmlewis commented on github/event_types.go
> +// The Webhook event name is "projects_v2_item"
```suggestion
// The Webhook event name is "projects_v2_item".
```

2023-08-13 15:28 UTC, gmlewis commented on github/event_types_test.go
> +
Please remove blank line.

2023-08-13 16:32 UTC, gmlewis approved these changes
Thank you, @nikpivkin !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.
(Maybe @evankanderson has time so that this can be merged before work is continued on #2865 ?)

2023-08-14 20:15 UTC, evankanderson approved these changes

2023-08-14 20:16 UTC, evankanderson commented
Not sure if my review/approval helps, but LGTM.  Double checked that the types seem to match the documentation.

2023-08-14 23:04 UTC, gmlewis commented
> Not sure if my review/approval helps, but LGTM. Double checked that the types seem to match the documentation.

Yes it does, as you are a valued contributor to this repo.  Thank you, @evankanderson !
Merging.

2023-08-14 23:05 UTC, merged