Fix SecretScanning API by switching arguments from url to json
google/go-github pull request #2871
Opened 2023-08-14 16:55 UTC by jentfoo

These structs were incorrectly defined with `url` parameters, instead these need to be encoded into `json` for the request.

2023-08-14 17:23 UTC, gmlewis requested changes
Thank you, @jentfoo !
Now that they are using `json` tags, we need to change the optional strings to pointers.

2023-08-14 17:23 UTC, gmlewis commented on github/secret_scanning.go
> +	State string `json:"state,omitempty"`
```suggestion
	State *string `json:"state,omitempty"`
```

2023-08-14 17:23 UTC, gmlewis commented on github/secret_scanning.go
> +	SecretType string `json:"secret_type,omitempty"`
```suggestion
	SecretType *string `json:"secret_type,omitempty"`
```

2023-08-14 17:24 UTC, gmlewis commented
Please run `go generate ./...` at the top of the repo and push (not force-push) the changes to this PR.
See CONTRIBUTING.md for details.

2023-08-14 18:07 UTC, gmlewis commented
It looks like you will also need to update the unit tests by changing some of the strings to `String(...)` so that their pointers are taken.

Please run "go test ./..." locally to make sure all tests pass before pushing your next commit.  Thanks.

2023-09-18 21:01 UTC, gmlewis commented
@jentfoo - we'll leave this PR open for a week or two, but if we haven't heard back from you, we'll close it as abandoned.

2023-09-18 21:37 UTC, jentfoo commented
@gmlewis This is a bug that should be addressed, however I don't have time to complete the requested test changes

2023-09-18 21:38 UTC, gmlewis commented
OK, thank you for the update, @jentfoo - I'll take a look when I get a chance.

2023-09-18 22:50 UTC, gmlewis commented
Hmmm... I'm looking at:
https://docs.github.com/en/enterprise-server@3.5/rest/secret-scanning/secret-scanning#list-secret-scanning-alerts-for-an-enterprise
and it shows that the parameters in question are indeed URL query parameters and not sent via JSON (which this PR is changing them to).

So let's back up a moment.

When you say "This is a bug that should be addressed"... could you please elaborate on the actual bug you are seeing?

What endpoint(s) are you calling?
What error messages do you get?
Do you have a simple test case that demonstrates the problem?

Unless I can better understand what the actual problem is, I'm going to have to close this PR as not having enough information to fix.

2023-09-18 23:32 UTC, jentfoo commented
> What endpoint(s) are you calling?

This PR was opened a while ago and I ultimately ended up switching to GraphQL for most of my needs.  So I don't fully recall why I was suggesting updating `SecretScanningAlertListOptions`.  It looks like based off your linked docs that recommendation may have been in error.

However `SecretScanningAlertUpdateOptions` is appears to me incorrect, here are the relevant docs: https://docs.github.com/en/enterprise-server@3.5/rest/secret-scanning/secret-scanning#update-a-secret-scanning-alert

I recall an API error when the current `github.Client.SecretScanning.UpdateAlert` is attempted with any configuration in the `SecretScanningAlertUpdateOptions` struct.

I apologize for not being able to help further right now, but I will try to answer questions as I am able.

2023-09-19 00:26 UTC, gmlewis commented
Ah, yes!  I see the problem now!  Thank you, @jentfoo !
I'll see what I can do here.

2023-09-19 00:36 UTC, gmlewis commented on github/github-accessors.go
> +
```suggestion
```

2023-09-19 00:59 UTC, gmlewis commented
Note that this PR is being replaced by #2934 since I was unable to edit the contents of this PR myself.

2023-09-19 14:32 UTC, closed without merging