Add support for enable/disable private vulnerability reporting on repositories
google/go-github pull request #2887
Opened 2023-08-19 07:44 UTC by vandanrohatgi

Closes https://github.com/google/go-github/issues/2883

- [x] go generate
- [x] go vet
- [x] go test

Please let me know if the method names are not descriptive enough or just need to be changed. 

Also, something that's been bugging me. In my previous [PR](https://github.com/google/go-github/pull/2869), I did some actual testing aside from the unit tests. While not present in [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) , is it advisable/necessary/optional to perform actual testing (importing the library, calling the new method and examine response).

2023-08-19 22:13 UTC, gmlewis requested changes
Thank you, @vandanrohatgi !
A few minor tweaks, please, then we will be ready for a second LGTM+Approval before merging.

2023-08-19 22:13 UTC, gmlewis commented on github/repos.go
> +func (s *RepositoriesService) EnablePrivateReporting(ctx context.Context, owner string, repo string) (*Response, error) {
```suggestion
func (s *RepositoriesService) EnablePrivateReporting(ctx context.Context, owner, repo string) (*Response, error) {
```

2023-08-19 22:13 UTC, gmlewis commented on github/repos.go
> +// Github API docs: https://docs.github.com/en/rest/repos/repos#enable-private-vulnerability-reporting-for-a-repository
```suggestion
// GitHub API docs: https://docs.github.com/en/rest/repos/repos#enable-private-vulnerability-reporting-for-a-repository
```

2023-08-19 22:13 UTC, gmlewis commented on github/repos.go
> +// Github API docs: https://docs.github.com/en/rest/repos/repos#disable-private-vulnerability-reporting-for-a-repository
```suggestion
// GitHub API docs: https://docs.github.com/en/rest/repos/repos#disable-private-vulnerability-reporting-for-a-repository
```

2023-08-19 22:13 UTC, gmlewis commented on github/repos.go
> +func (s *RepositoriesService) DisablePrivateReporting(ctx context.Context, owner string, repo string) (*Response, error) {
```suggestion
func (s *RepositoriesService) DisablePrivateReporting(ctx context.Context, owner, repo string) (*Response, error) {
```

2023-08-19 22:17 UTC, gmlewis commented
> Also, something that's been bugging me. In my previous [PR](https://github.com/google/go-github/pull/2869), I did some actual testing aside from the unit tests. While not present in [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) , is it advisable/necessary/optional to perform actual testing (importing the library, calling the new method and examine response).

In this repo, we do not typically add to the integration tests anymore.
They were extremely helpful in the early design of the repo, but in my opinion, the surface area of this API is so huge that it would be an onerous task to attempt to keep up-to-date in addition to the unit tests.

Having said that, we place a high value on unit tests in this repo and want every endpoint to be exercised "round-trip" with an in-memory http server to verify that every looks like it should work in real practice.

So you are proceeding along just as planned, and we really appreciate your contributions, @vandanrohatgi !

Keep up the great work!  😁 ❤️

2023-08-20 03:34 UTC, vandanrohatgi commented
Thank you for making this project such a pleasure to work with!

2023-08-20 12:08 UTC, gmlewis approved these changes
Thank you, @vandanrohatgi !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-08-20 12:38 UTC, mnafees commented
LGTM 👍🏽

2023-08-20 12:50 UTC, gmlewis commented
Thank you, @mnafees !
Merging.

2023-08-20 12:51 UTC, merged