Add support for dependabot_alert webhook event
google/go-github pull request #2888
Opened 2023-08-20 03:26 UTC by nikpivkin

Closes #2790 

Added support for [dependabot_alert](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#dependabot_alert) webhook event.

2023-08-21 00:41 UTC, gmlewis requested changes
Thank you, @nikpivkin !

2023-08-21 00:41 UTC, gmlewis commented on github/event_types.go
> +	Alert  DependabotAlert `json:"alert"`
```suggestion
	Alert  *DependabotAlert `json:"alert,omitempty"`
```

2023-08-21 00:41 UTC, gmlewis commented on github/event_types.go
> +	Sender       *User         `json:"sender,omitempty"`
```suggestion
	// The following fields are only populated by Webhook events.
	Installation *Installation `json:"installation,omitempty"`
	Enterprise   *Enterprise   `json:"enterprise,omitempty"`
	Repo         *Repository   `json:"repository,omitempty"`
	Sender       *User         `json:"sender,omitempty"`

	// The following field is only present when the webhook is triggered on
	// a repository belonging to an organization.
	Organization *Organization `json:"organization,omitempty"`
```

2023-08-21 15:28 UTC, gmlewis approved these changes
Thank you, @nikpivkin !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-08-29 18:02 UTC, WillAbides approved these changes

2023-08-29 18:08 UTC, gmlewis commented
Thank you, @WillAbides !
Merging.

2023-08-29 18:08 UTC, merged