Add missing CodeScanning endpoints
google/go-github pull request #2900
Opened 2023-08-26 09:50 UTC by jporzucek

Fixes https://github.com/google/go-github/issues/2899

2023-08-26 19:05 UTC, gmlewis requested changes
Thank you, @jporzucek .
Just a few changes to make, please, mostly relating to capitalizations, then we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2023-08-26 19:05 UTC, gmlewis commented on github/code-scanning.go
> +// GitHub API docs: https://docs.github.com/en/rest/code-scanning#get-information-about-a-sarif-upload
Please double-check your URLs, as this one didn't work.

```suggestion
// GitHub API docs: https://docs.github.com/en/free-pro-team@latest/rest/code-scanning/code-scanning?apiVersion=2022-11-28#get-information-about-a-sarif-upload
```

2023-08-26 19:05 UTC, gmlewis commented on github/code-scanning.go
> +func (s *CodeScanningService) GetSarif(ctx context.Context, owner, repo, id string) (*SarifUpload, *Response, error) {
```suggestion
func (s *CodeScanningService) GetSARIF(ctx context.Context, owner, repo, sarifID string) (*SARIFUpload, *Response, error) {
```

2023-08-26 19:05 UTC, gmlewis commented on github/code-scanning.go
> +// DeleteAnalysis represents a successful deletion of a code scanning analysis
```suggestion
// DeleteAnalysis represents a successful deletion of a code scanning analysis.
```

2023-08-26 19:05 UTC, gmlewis commented on github/code-scanning.go
> +
Please delete this line, as it will break the auto-generated godoc comment processor.

2023-08-26 19:05 UTC, gmlewis commented on github/code-scanning.go
> +// ListCodeqlDatabases lists the CodeQL databases that are available in a repository.
```suggestion
// ListCodeQLDatabases lists the CodeQL databases that are available in a repository.
```

2023-08-26 19:05 UTC, gmlewis commented on github/code-scanning.go
> +// GetCodeqlDatabase gets a CodeQL database for a language in a repository.
```suggestion
// GetCodeQLDatabase gets a CodeQL database for a language in a repository.
```

2023-08-28 19:54 UTC, gmlewis approved these changes
Thank you, @jporzucek !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-08-30 14:35 UTC, WillAbides approved these changes

2023-08-30 14:41 UTC, gmlewis commented
Thank you, @WillAbides !
Merging.

2023-08-30 14:41 UTC, merged