Added Repository Security Advisories APIs
google/go-github pull request #2902
Opened 2023-08-26 11:53 UTC by anishrajan25

Relates to #2866

2023-08-28 14:48 UTC, anishrajan25 commented
@gmlewis The PR is ready for review. Could you please have a look as per your availability?

2023-08-28 20:01 UTC, gmlewis requested changes
I don't have time for a full review right now, but at a quick glance, it looks like you are defining a whole bunch of new structs... possibly more than necessary.  We try to reuse structs when the meaning is similar if possible.

It also looks like you are redefining `ListOptions` and/or `ListCursorOptions` when they could be embedded into other options... please look around this repo for examples on how to do this.

Third, all new structs must have complete sentences ending in a period for the auto-generated godocs to be formatted correctly.  Please fix this.

Additionally, it looks like there are linting and/or test errors that need fixing. Please address.

2023-09-10 19:45 UTC, anishrajan25 commented
@gmlewis I have analysed the existing structs and prepared a document capturing the possibilities of embedding some structs to prevent redefining some fields.

Could you please have a look at [this document](https://docs.google.com/document/d/10ezC0VHeUWk3WBNZJjOlOld97XOLeRQpNA34Xsz0BFM/edit?usp=sharing) and add comments wherever necessary to provide your inputs?

I will fix the comments to end with period, linting, and test errors in the next commit along with updating the struct definitions.

2023-09-10 19:51 UTC, gmlewis commented
I'll be back on 9/18 when I can take a look at this. Sorry for the delay and inconvenience.

2023-09-11 05:44 UTC, anishrajan25 commented
No worries. You can have a look whenever you are available ✌🏼

2023-09-18 20:47 UTC, gmlewis commented
@anishrajan25 - I'm back, but none of the comments I left above:
https://github.com/google/go-github/pull/2902#pullrequestreview-1599004532
have been addressed.  Please fix these issues before we can continue.

2023-09-30 13:51 UTC, anishrajan25 commented
Hi @gmlewis , apologies for the delay in response.

I have created [this document](https://docs.google.com/document/d/10ezC0VHeUWk3WBNZJjOlOld97XOLeRQpNA34Xsz0BFM/edit?usp=sharing), capturing the possibilities of embedding some structs to prevent redefining some fields. 
Could you please have a look and add comments wherever necessary to provide your input?

2023-10-02 05:17 UTC, anishrajan25 commented
I have updated the existing structs and reused them instead of creating new ones wherever possible. I have fixed the comments as well. @gmlewis Could you please have a look?

2023-10-02 12:10 UTC, gmlewis requested changes

2023-10-02 12:10 UTC, gmlewis commented on github/security_advisories.go
> +// ListRepositorySecurityAdvisoriesOptions specifies the optional parameters to lists the repository security advisories.
```suggestion
// ListRepositorySecurityAdvisoriesOptions specifies the optional parameters to list the repository security advisories.
```

2023-10-02 12:10 UTC, gmlewis commented on github/security_advisories.go
> +// Github API docs: https://docs.github.com/en/rest/security-advisories/repository-advisories?apiVersion=2022-11-28#list-repository-security-advisories-for-an-organization
```suggestion
// GitHub API docs: https://docs.github.com/en/rest/security-advisories/repository-advisories?apiVersion=2022-11-28#list-repository-security-advisories-for-an-organization
```

2023-10-02 12:10 UTC, gmlewis commented on github/security_advisories.go
> +// Github API docs: https://docs.github.com/en/enterprise-cloud@latest/rest/security-advisories/repository-advisories?apiVersion=2022-11-28#list-repository-security-advisories
```suggestion
// GitHub API docs: https://docs.github.com/en/enterprise-cloud@latest/rest/security-advisories/repository-advisories?apiVersion=2022-11-28#list-repository-security-advisories
```

2023-10-02 12:10 UTC, gmlewis commented on github/security_advisories.go
> +func (s *SecurityAdvisoriesService) ListRepositorySecurityAdvisories(ctx context.Context, owner string, repo string, opt *ListRepositorySecurityAdvisoriesOptions) ([]*SecurityAdvisory, *Response, err
```suggestion
func (s *SecurityAdvisoriesService) ListRepositorySecurityAdvisories(ctx context.Context, owner, repo string, opt *ListRepositorySecurityAdvisoriesOptions) ([]*SecurityAdvisory, *Response, error) {
```

2023-10-02 15:44 UTC, gmlewis requested changes

2023-10-02 15:44 UTC, gmlewis commented on github/security_advisories_test.go
> +	} else if !strings.Contains(err.Error(), "json: cannot unmarshal number into Go struct field RepoSecurityAdvisory.ghsa_id of type string") {
```suggestion
	} else if !strings.Contains(err.Error(), "json: cannot unmarshal number into Go struct field SecurityAdvisory.ghsa_id of type string") {
```

2023-10-02 15:45 UTC, gmlewis commented
Please check that test pass locally with `go test ./...` before pushing.

2023-10-02 19:22 UTC, anishrajan25 commented
There are some failing test cases. I will update once the test cases are fixed.

2023-10-03 08:26 UTC, anishrajan25 commented
@gmlewis I have fixed the test cases as well. All the tests are passing on my local

2023-10-03 12:33 UTC, gmlewis commented
Please run `go generate ./...` as described in CONTRIBUTING.md and push the results to this PR.

2023-10-04 11:33 UTC, gmlewis approved these changes
Thank you, @anishrajan25 !
LGTM.

Awaiting second LGTM+Approval from any other contributor to the repo before merging.

2023-10-05 08:28 UTC, valbeat approved these changes

2023-10-05 11:53 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2023-10-05 11:53 UTC, merged