Update constructors
google/go-github pull request #2904
Opened 2023-08-28 22:57 UTC by WillAbides

Closes #2897

After experimenting with implementing #2897, I think this ends up with better usage for end users.

This deprecates `github.NewTokenClient` and `github.NewEnterpriseClient` and replaces them with `Client.WithAuthToken` and `Client.WithEnterpriseURLs`.

Now you can create an authenticated client for an enterprise server with:

```go
client, err := github.NewClient(nil).WithAuthToken(token).WithEnterpriseURLs(baseURL,uploadURL)
```

There is no need for users import `github.com/x/oauth2` anymore.

I opted for this implementation over my `WithOptions` proposal the error returned from `WithOptions` means that most uses of go-github would have an unnecessary error check.

```go
client err := github.NewClient(nil).WithOptions(github.WithAuthToken(token))
if err != nil {
  panic(err)
}
```

vs

```go
client := github.NewClient(nil).WithAuthToken(token)
```

2023-08-28 23:51 UTC, gmlewis requested changes
This looks great, @WillAbides !
Just a few minor nits, please, then we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2023-08-28 23:51 UTC, gmlewis commented on github/github.go
> +// Deprecated: Use NewClient(httpClient).WithOptions(WithEnterpriseURLs(baseURL, uploadURL)) instead.
We need the first two lines to make the auto-generated godoc documentation read correctly.

```suggestion
// NewEnterpriseClient returns a new GitHub API client with provided
// base URL and upload URL (often is your GitHub Enterprise hostname).
//
// Deprecated: Use NewClient(httpClient).WithOptions(WithEnterpriseURLs(baseURL, uploadURL)) instead.
```

2023-08-28 23:51 UTC, gmlewis commented on github/github.go
> +	return NewClient(httpClient).WithEnterpriseURLs(baseURL, uploadURL)
This seems like a really easy thing to add a test to make codecov happy.

2023-08-28 23:51 UTC, gmlewis commented on github/github.go
> +		clone.client = &http.Client{}
This also seems like a really easy thing to add a test to make codecov happy.

2023-08-29 14:44 UTC, WillAbides commented
@gmlewis Updated with your suggestions.

As an aside, is there a way to get a preview of what codecov is going to report before pushing? I looked for a way to run it locally, and it appears to require an API token and membership in the right org.

2023-08-29 15:02 UTC, gmlewis commented
> As an aside, is there a way to get a preview of what codecov is going to report before pushing? I looked for a way to run it locally, and it appears to require an API token and membership in the right org.

Not that I'm aware of.

Sometimes, to get an idea of what it might report, I run this locally first:

```bash
$ cat coverage-web.sh
#!/bin/bash -ex
go test -coverprofile=cover.out ./...
go tool cover -html cover.out
```

but it is obviously not the same.

2023-08-29 15:04 UTC, gmlewis approved these changes
Awesome!  Thank you, @WillAbides !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-08-29 17:51 UTC, WillAbides commented
I made a script to preview whether codecov will fail your PR: https://gist.github.com/WillAbides/e0bbffccb34d9922cecb2ab9d66defec

2023-08-29 18:10 UTC, gmlewis commented
> I made a script to preview whether codecov will fail your PR: https://gist.github.com/WillAbides/e0bbffccb34d9922cecb2ab9d66defec

Thank you, @WillAbides !  That's fantastic!

2023-08-31 19:26 UTC, gmlewis commented
Thank you, @sridharavinash !
Merging.

2023-08-31 19:27 UTC, merged