Support for Required Workflows
google/go-github pull request #2979
Opened 2023-10-31 15:18 UTC by claystation

A suggestion to add support for Required Workflows in Github API. 
This solves #2978 .

2023-11-03 15:25 UTC, gmlewis requested changes
Thank you, @claystation !
After a few tweaks, we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2023-11-03 15:25 UTC, gmlewis commented on github/repos_rules.go
> +	Sha          string `json:"sha,omitempty"`
```suggestion
	Ref          *string `json:"ref,omitempty"`
	RepositoryID *int64 `json:"repository_id,omitempty"`
	Sha          *string `json:"sha,omitempty"`
```

2023-11-03 15:25 UTC, gmlewis commented on github/repos_rules.go
> +	RequiredWorkflows []RuleRequiredWorkflow `json:"workflows"`
```suggestion
	RequiredWorkflows []*RuleRequiredWorkflow `json:"workflows"`
```

2023-11-03 15:25 UTC, gmlewis commented on github/repos_rules.go
> +// NewRequiredStatusChecksRule creates a rule to require which status checks must pass before branches can be merged into a branch rule.
```suggestion
// NewRequiredWorkflowsRule creates a rule to require which status checks must pass before branches can be merged into a branch rule.
```

2023-11-03 16:08 UTC, claystation commented
Hey @gmlewis ! Thanks for the review :) I updated the code to reflect the correct suggestions!

2023-11-03 16:20 UTC, gmlewis commented on github/repos_rules.go
> +	Sha          string `json:"sha,omitempty"`
Please add the pointers to the `omitempty` fields.

```suggestion
	Ref          *string `json:"ref,omitempty"`
	RepositoryID *int64 `json:"repository_id,omitempty"`
	Sha          *string `json:"sha,omitempty"`
```

2023-11-06 13:46 UTC, gmlewis commented
It looks like some `gofmt` needs to be called, then we should be good to move forward on this PR.

2023-11-07 09:39 UTC, claystation commented
Hey @gmlewis! I did a `gofmt` and generated files as requested in the check :) Should be good to go now!

2023-11-07 14:35 UTC, gmlewis approved these changes
Thank you, @claystation !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-11-08 16:36 UTC, valbeat approved these changes

2023-11-08 16:37 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2023-11-08 16:37 UTC, merged