Escape package names to support names which include a slash
google/go-github pull request #3002
Opened 2023-11-24 10:22 UTC by bn4t

Package names aren't escaped before being added to the url.
E.g. `orgs/foo/packages/container/foo/bar` instead of `orgs/foo/packages/container/foo%2Fbar`

This causes 404 errors for such packages.

2023-11-24 13:32 UTC, gmlewis requested changes
Thank you, @bn4t !

For each of the modified methods, could you please add a godoc comment (since this is a change of behavior) and also a unit test that demonstrates the new path escaping?

For example:

```go
// Note that packageName is escaped for the URL path so that you don't need to.
```

2023-12-01 09:49 UTC, bn4t commented
@gmlewis Would it be fine if I just changed the existing tests to use a package name with a slash or do cou want me to write one/multiple new tests for this?

2023-12-01 17:25 UTC, gmlewis commented
> @gmlewis Would it be fine if I just changed the existing tests to use a package name with a slash or do you want me to write one/multiple new tests for this?

I think it is totally fine to modify the existing tests.  Thanks.

2023-12-04 12:55 UTC, bn4t commented
@gmlewis Okay, pushed it. Thanks for handholding me through this, this really shouldn't have taken so long. My fault for not checking the contributing guidelines in detail.

2023-12-04 13:02 UTC, gmlewis commented
> @gmlewis Okay, pushed it. Thanks for handholding me through this, this really shouldn't have taken so long. My fault for not checking the contributing guidelines in detail.

No problem, we do have a lot of automation in this repo that is not immediately obvious.

2023-12-04 13:04 UTC, gmlewis approved these changes
Thank you, @bn4t !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-12-15 07:44 UTC, valbeat approved these changes
LGTM!

2023-12-16 01:01 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2023-12-16 01:01 UTC, merged