Remove ambiguous fields from AuditEntry
google/go-github pull request #3017
Opened 2023-12-05 21:36 UTC by WillAbides

closes #3016

In https://github.com/google/go-github/issues/3016#issuecomment-1841102405 I suggested that AuditEntry fields should be limited to what is in the openapi description. I have since spoken with some people at GitHub and learned that the openapi description is outdated and there are discrepancies between the description and the json being returned by the api.

Instead of limiting AuditEntry to what is in the openapi description, this PR reduces AuditEntry to fields that are known to be the same type across all events regardless of the openapi description. The rest of the fields are now available in `AuditEntry.AdditionalFields` as a `map[string]any`

This is a breaking change.

2023-12-06 01:27 UTC, gmlewis requested changes
Thank you, @WillAbides !
Just a few nits, please, then we will be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2023-12-06 01:27 UTC, gmlewis commented on github/orgs_audit_log.go
> +	if err != nil {
nit

```suggestion
	if err := json.Unmarshal(data, &v); err != nil {
```

2023-12-06 01:27 UTC, gmlewis commented on github/orgs_audit_log.go
> +	if err != nil {
```suggestion
	if err := json.Unmarshal(rawDefinedFields, &definedFields); err != nil {
```

2023-12-06 01:27 UTC, gmlewis commented on github/orgs_audit_log.go
> +	if err != nil {
```suggestion
	if err := json.Unmarshal(data, &v.AdditionalFields); err != nil {
```

2023-12-06 01:27 UTC, gmlewis commented on github/orgs_audit_log.go
> +		if defined || val == nil {
```suggestion
		if _, ok := definedFields[key]; ok || val == nil {
```

2023-12-06 01:27 UTC, gmlewis commented on github/orgs_audit_log.go
> +	if err != nil {
```suggestion
	if err := json.Unmarshal(defBytes, &resMap); err != nil {
```

2023-12-06 01:27 UTC, gmlewis commented on github/orgs_audit_log.go
> +		if defined {
```suggestion
		if _, ok := resMap[key]; ok {
```

2023-12-06 01:27 UTC, gmlewis commented on github/orgs_audit_log.go
> +			return nil, fmt.Errorf("unexpected field in AdditionalFields: %s", key)
```suggestion
			return nil, fmt.Errorf("unexpected field in AdditionalFields: %v", key)
```

2023-12-06 16:37 UTC, gmlewis approved these changes
Thank you, @WillAbides !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-12-17 12:16 UTC, valbeat approved these changes
LGTM!

2023-12-17 12:41 UTC, gmlewis commented
Thank you @valbeat !
Merging.

2023-12-17 19:48 UTC, gmlewis commented
Sorry, I'm going to have to work on this one because of all the other recent merges. Hopefully tomorrow I can work on it.

2023-12-18 01:37 UTC, gmlewis commented
Note that the new `Referrer` field added in #3032 has been moved in this PR to the `AdditionalFields` map.

2023-12-18 01:38 UTC, merged