Add repo GetAllCustomPropertyValues
google/go-github pull request #3020
Opened 2023-12-05 23:10 UTC by liaodaniel

Closes https://github.com/google/go-github/issues/3014.

Signed-off-by: Daniel Liao <10663736+liaodaniel@users.noreply.github.com>

2023-12-06 01:30 UTC, gmlewis requested changes
Thank you, @liaodaniel !
Just a few tweaks, please, then we will be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2023-12-06 01:30 UTC, gmlewis commented on github/repos_properties.go
> +package github
```suggestion
// Copyright 2023 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package github
```

2023-12-06 01:30 UTC, gmlewis commented on github/repos_properties.go
> +// GetAllCustomPropertyValues gets all custom properties values that are set for a repository.
```suggestion
// GetAllCustomPropertyValues gets all custom property values that are set for a repository.
```

2023-12-06 01:30 UTC, gmlewis commented on github/repos_properties.go
> +	u := fmt.Sprintf("repos/%s/%s/properties/values", org, repo)
```suggestion
	u := fmt.Sprintf("repos/%v/%v/properties/values", org, repo)
```

2023-12-06 01:30 UTC, gmlewis commented on github/repos_properties.go
> +func (s *RepositoriesService) GetAllCustomPropertyValues(ctx context.Context, org string, repo string) ([]*CustomPropertyValue, *Response, error) {
```suggestion
func (s *RepositoriesService) GetAllCustomPropertyValues(ctx context.Context, org, repo string) ([]*CustomPropertyValue, *Response, error) {
```

2023-12-06 05:24 UTC, liaodaniel commented
Thank you @gmlewis, need to pay more attention to copying and pasting 😅

2023-12-06 13:21 UTC, gmlewis approved these changes
Thank you, @liaodaniel !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-12-17 16:41 UTC, valbeat approved these changes
LGTM!

2023-12-17 19:45 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2023-12-17 19:46 UTC, merged