Support temporary private fork creation via API
google/go-github pull request #3025
Opened 2023-12-09 15:54 UTC by Kiyo510

resolved: #3007

2023-12-09 22:18 UTC, gmlewis requested changes
Thank you, @Kiyo510 !
One minor nit, please, and then we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2023-12-09 22:18 UTC, gmlewis commented on github/security_advisories.go
> +// CreateTemporaryPrivateFork Create a temporary private fork to collaborate on fixing a security vulnerability in your repository.
```suggestion
// CreateTemporaryPrivateFork creates a temporary private fork to collaborate on fixing a security vulnerability in your repository.
```

2023-12-10 10:11 UTC, Kiyo510 commented
@gmlewis 
Thanks for reviewing my PR.
Since I made a modification, please check it out again.

2023-12-10 12:20 UTC, gmlewis approved these changes
Thanks, @Kiyo510 !
LGTM.

Awaiting a second LGTM+Approval from any other contributor to this repo before merging.

2023-12-15 08:49 UTC, valbeat approved these changes
LGTM!

2023-12-15 22:22 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2023-12-15 22:22 UTC, merged