feat: scanning validity checks
google/go-github pull request #3026
Opened 2023-12-11 14:06 UTC by tomasz-adam-skrzypczak

Solves #3006

2023-12-11 14:33 UTC, tomasz-adam-skrzypczak commented
I've managed to accept CLA and added my github email address as an alternative but I cannot rerun workflow (and don't want to commit pointless commits). @gmlewis could you rerun workflow for me?

2023-12-11 15:08 UTC, gmlewis requested changes

2023-12-11 15:08 UTC, gmlewis commented on github/repos.go
> +	SecretScanningValidityChecks *SecretScanningValidityChecks `json:"secret_scanning_validity_checks"`
```suggestion
	SecretScanningValidityChecks *SecretScanningValidityChecks `json:"secret_scanning_validity_checks,omitempty"`
```

2023-12-11 15:08 UTC, gmlewis commented on github/repos.go
> +// Specifies the state of secret scanning validity checks on a repository.
```suggestion
// SecretScanningValidityChecks represents the state of secret scanning validity checks on a repository.
```

2023-12-11 15:08 UTC, gmlewis commented on github/repos.go
> +// Github API docs: https://docs.github.com/en/enterprise-cloud@latest/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-security-and-analysi
"Github" => "GitHub" - but if you run the commands in step 4 of CONTRIBUTING.md, then this will most likely get fixed automatically.

2023-12-12 01:42 UTC, gmlewis requested changes
Thank you, @tomasz-adam-skrzypczak !
Just one small nit, please, then we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2023-12-12 01:42 UTC, gmlewis commented on github/repos.go
> +}
I'm pretty sure this can be completely removed.

2023-12-12 13:15 UTC, gmlewis approved these changes
Thank you, @tomasz-adam-skrzypczak !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2023-12-12 13:16 UTC, gmlewis commented
Whups, please run step 4 of CONTRIBUTING.md and push the results.

2023-12-14 07:48 UTC, rufusnufus approved these changes
LGTM

2023-12-14 14:13 UTC, gmlewis commented
Thank you, @rufusnufus !
Merging.

2023-12-14 14:14 UTC, merged