feat: add support for deployment protection rules
google/go-github pull request #3050
Opened 2024-01-14 07:02 UTC by abhishekbiyala

Fixes https://github.com/google/go-github/issues/3022

2024-01-14 21:13 UTC, gmlewis requested changes
Thank you, @abhishekbiyala !
Just a few minor tweaks, please, then we will be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2024-01-14 21:13 UTC, gmlewis commented on github/repos_deployment_protection_rules.go
> +// Copyright 2023 The go-github AUTHORS. All rights reserved.
```suggestion
// Copyright 2024 The go-github AUTHORS. All rights reserved.
```

2024-01-14 21:13 UTC, gmlewis commented on github/repos_deployment_protection_rules.go
> +type CustomDeploymentProtectionRuleApp struct {
Please add a descriptive godoc-style comment for this exported struct.

2024-01-14 21:13 UTC, gmlewis commented on github/repos_deployment_protection_rules.go
> +// ListDeploymentProtectionRuleResponse represents the format of response that comes back when you list deployment protection rules.
```suggestion
// ListDeploymentProtectionRuleResponse represents the response that comes back when you list deployment protection rules.
```

2024-01-14 21:13 UTC, gmlewis commented on github/repos_deployment_protection_rules.go
> +// ListCustomDeploymentRuleIntegrationsResponse represents the slightly different format of response that comes back when you list custom deployment rule integrations.
```suggestion
// ListCustomDeploymentRuleIntegrationsResponse represents the slightly different response that comes back when you list custom deployment rule integrations.
```

2024-01-14 21:13 UTC, gmlewis commented on github/repos_deployment_protection_rules.go
> +	Apps       []*CustomDeploymentProtectionRuleApp `json:"available_custom_deployment_protection_rule_integrations,omitempty"`
How about "Apps" => "AvailableIntegrations"?

2024-01-14 21:13 UTC, gmlewis commented on github/repos_deployment_protection_rules.go
> +// GetAllDeploymentProtectionRules get all the deployment protection rules for an environment.
```suggestion
// GetAllDeploymentProtectionRules gets all the deployment protection rules for an environment.
```

2024-01-14 21:47 UTC, gmlewis approved these changes
Thank you, @abhishekbiyala !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-02-01 17:43 UTC, fchimpan commented
Hi, @abhishekbiyala 
Thanks your implementation. LGTM!

2024-02-01 17:56 UTC, gmlewis commented
Thank you, @fchimpan !
Merging.

2024-02-01 17:57 UTC, merged