Add ListWorkflowJobsAttempt method to ActionsService
google/go-github pull request #3060
Opened 2024-01-26 17:48 UTC by fchimpan

fix #3059 

Add support ListWorkflowJobsAttempt API. 
https://docs.github.com/rest/actions/workflow-jobs#list-jobs-for-a-workflow-run-attempt

2024-01-26 18:26 UTC, gmlewis requested changes
Thank you, @fchimpan !
This looks like a great start apart from the code coverage.

I've added a suggestion that should hopefully clear up the coverage tests.

2024-01-26 18:26 UTC, gmlewis commented on github/actions_workflow_jobs_test.go
> +}
```suggestion

	const methodName = "ListWorkflowJobsAttempt"
	testBadOptions(t, methodName, func() (err error) {
		_, _, err = client.Actions.ListWorkflowJobsAttempt(ctx, "\n", "\n", -1, -1, opts)
		return err
	})
	testNewRequestAndDoFailure(t, methodName, client, func() (*Response, error) {
		got, resp, err := client.Actions.ListWorkflowJobsAttempt(ctx, "o", "r", 29679449, 1, opts)
		if got != nil {
			t.Errorf("testNewRequestAndDoFailure %v = %#v, want nil", methodName, got)
		}
		return resp, err
	})
```

2024-01-26 18:35 UTC, gmlewis approved these changes
Thank you, @fchimpan !
LGTM

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-01-26 18:36 UTC, fchimpan commented
@gmlewis 

Thanks for your advice. I was already working on improving the test coverage before I noticed your comments, so there may have been some overlap. I would appreciate it if you could review the changes. I look forward to your feedback.

Best regards,

2024-01-26 18:49 UTC, fchimpan commented
@gmlewis 
Thank you for the comment. I understand and am happy to help. 
I have an interest in this repository, so I will definitely cooperate.

Since I don't have the authority to approve pull requests, should I just leave comments on the PR if I have any suggestions?

2024-01-26 20:44 UTC, gmlewis commented
Thank you, @fchimpan !
Yes, feel free to leave comments, and when you are satisfied with the changes, you can say "LGTM" (Looks Good To Me) and I will take that as approval.

2024-01-27 01:59 UTC, fchimpan commented
Thank you @gmlewis 
Understood, I will check it out.

By the way, sometimes I come across APIs that are not yet implemented. In such cases, is it alright if I propose a PR like I did this time?

Thank you in advance.

2024-01-27 02:10 UTC, gmlewis commented
> By the way, sometimes I come across APIs that are not yet implemented. In such cases, is it alright if I propose a PR like I did this time?

Absolutely!  We welcome all contributions.
The GitHub v3 API is amazingly huge and constantly updating, so we definitely welcome the help.
Thank you!

2024-02-09 12:36 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2024-02-09 12:37 UTC, merged