chore!: change Hook Config field from map to *HookConfig
google/go-github pull request #3073
Opened 2024-02-13 21:36 UTC by himazawa

Closes #3072

2024-02-14 08:11 UTC, himazawa commented
I would like to sign the CLA but there is no way to add the `noreply.github.com` email to the CLA account.

2024-02-14 14:51 UTC, gmlewis requested changes
Thank you, @himazawa.

2024-02-14 14:51 UTC, gmlewis commented on github/hooks_config.go
> +// HookConfig describes metadata about a webhook configuration.
Instead of creating a file with only one struct in it, let's please move this to `repos_hooks_configuration.go` where it is most heavily used.

2024-02-14 14:52 UTC, gmlewis commented
> I would like to sign the CLA but there is no way to add the `noreply.github.com` email to the CLA account.

Did you read the instructions for email addresses here: https://github.com/google/go-github/pull/3073/checks?check_run_id=21540833172 ?

2024-02-14 18:01 UTC, gmlewis commented
Well, looks like you got it resolved whatever the problem was.

2024-02-14 18:02 UTC, gmlewis commented
Please run step 4 of CONTRIBUTING.md and then push (not force-push) the changes to this PR.

2024-02-14 18:19 UTC, himazawa commented
Done

2024-02-14 19:03 UTC, gmlewis approved these changes
Thank you, @himazawa !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-02-17 05:32 UTC, valbeat approved these changes
LGTM!

2024-02-17 14:56 UTC, gmlewis commented
Thank you, @valbeat !
Merging.

2024-02-17 15:10 UTC, merged