Ganeshkumarsv set custom property repositories
google/go-github pull request #3109
Opened 2024-03-23 22:18 UTC by ganeshkumarsv

2024-03-24 00:35 UTC, gmlewis commented
Thank you, @ganeshkumarsv !
I saw the commit titled "no idea what im doing" and thought I might help out...  In CONTRIBUTING.md, we have some helpful tips that should assist you.  Please let me know if you have any question, but it looks like you are on the right track.  You can also look at some of the other files for examples on code coverage.

2024-03-28 14:34 UTC, ganeshkumarsv commented
> Thank you, @ganeshkumarsv ! I saw the commit titled "no idea what im doing" and thought I might help out... In CONTRIBUTING.md, we have some helpful tips that should assist you. Please let me know if you have any question, but it looks like you are on the right track. You can also look at some of the other files for examples on code coverage.

Thanks for commenting @gmlewis. Running metadata.sh makes modification for a lot of URLs and erroring out. I don't see a way to update openapi configs only the one endpoint i'm updating. Any help appreciated. Thank you 🙇

2024-03-28 14:54 UTC, gmlewis commented
> Thanks for commenting @gmlewis. Running metadata.sh makes modification for a lot of URLs and erroring out. I don't see a way to update openapi configs only the one endpoint i'm updating. Any help appreciated. Thank you 🙇

You shouldn't have to deal with the metadata or OpenAPI stuff... you should only have to make sure your formatting has been fixed and the generator has been run, and you can revert any changes made to the metadata.

2024-03-28 15:13 UTC, ganeshkumarsv commented
I tried running `go run github/gen-accessors.go` but it is not generating anything. Am i missing something?

2024-03-28 15:37 UTC, ganeshkumarsv commented
I removed my changes from `openapi_operations.yaml` as u mentioned. The linter fails with the error `could not find operation "PATCH /repos/{owner}/{repo}/properties/values" in openapi_operations.yaml` 

Can I know how i can fix this error?

2024-03-28 18:34 UTC, gmlewis commented
@ganeshkumarsv - now that #3104 is merged, please try to update this branch using `git merge master` and see if that solves the problems you were seeing before.

2024-03-28 19:23 UTC, ganeshkumarsv commented
Thanks @gmlewis. I updated the branch and it fixed the linter. All the checks are passing now.

2024-03-28 19:41 UTC, gmlewis requested changes
Thank you, @ganeshkumarsv !
Just one minor tweak, please, then we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2024-03-28 19:41 UTC, gmlewis commented on github/repos_properties.go
> +		CustomPropertyValues: customPropertyValues,
```suggestion
		Properties []*CustomPropertyValue `json:"properties"`
	}{
		Properties: customPropertyValues,
```

2024-03-28 23:02 UTC, gmlewis approved these changes
Thank you, @ganeshkumarsv !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-03-29 14:59 UTC, ganeshkumarsv commented
@liaodaniel I need one more approval to merge this PR. Can you please review? 🙇

2024-03-29 15:22 UTC, AbbanMustafa approved these changes

2024-03-29 15:38 UTC, merged

2024-04-01 18:23 UTC, ganeshkumarsv commented
@gmlewis Thanks for merging. Is it possible to create a new release?

2024-04-01 19:03 UTC, gmlewis commented
> @gmlewis Thanks for merging. Is it possible to create a new release?

This is now released in v61: https://github.com/google/go-github/releases/tag/v61.0.0