added support for merge queue ruleset JSON unmarshalling
google/go-github pull request #3131
Opened 2024-04-18 17:38 UTC by Matthew-Reidy

Added support for respository ruleset merge_queue JSON unmarshalling code with accompanying tests per issue [google#3098](https://github.com/google/go-github/issues/3098)

2024-04-18 17:45 UTC, gmlewis requested changes
Thank you, @Matthew-Reidy !
Just a couple minor tweaks, please, then we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2024-04-18 17:45 UTC, gmlewis commented on AUTHORS
> +Matthew Reidy <matthewreidy5@gmail.com>
Please keep these lines sorted alphabetically, as an automated tool (run every few months) is usually used to update this list.

2024-04-18 17:45 UTC, gmlewis commented on github/repos_rules.go
> +	case "creation", "deletion", "required_linear_history", "required_signatures", "non_fast_forward", "merge_queue":
I know these weren't sorted before, but would you mind sorting them now, please?

2024-04-18 17:45 UTC, gmlewis commented on github/repos_rules.go
> +
No need for this extra blank line, please remove.

2024-04-18 17:49 UTC, Matthew-Reidy commented
Sure thing. I'll get I'll fix those items shortly

2024-04-18 18:20 UTC, gmlewis approved these changes
Thank you, @Matthew-Reidy !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-04-19 00:03 UTC, liaodaniel commented on github/repos_rules.go
> +// NewMergeQueueRule creates a rule to only allow users with bypass permission to create matching refs.
```suggestion
// NewMergeQueueRule creates a rule to only allow merges via a merge queue.
```

2024-04-19 00:04 UTC, liaodaniel commented
Just a minor comment to update but looks good otherwise

2024-04-19 00:16 UTC, Matthew-Reidy commented
changes to that comment have been made

2024-04-19 00:18 UTC, liaodaniel approved these changes
LGTM

2024-04-19 01:25 UTC, merged