issue3106 - Allow an empty array of repo ids as a request parameter
google/go-github pull request #3155
Opened 2024-04-26 17:08 UTC by Matthew-Reidy

fixes [issue3106](https://github.com/google/go-github/issues/3106)

Add extra endpoint function that allows client to pass an empty array of repository ids to the installations/<install_id>/access_tokens endpoint as a parameter. Response lists all repositories in an installation.

2024-04-27 15:26 UTC, gmlewis commented on github/apps.go
> +// CreateInstallationTokenListRepos creates a new installation token with an empty repository list as a parameter.
I'm thinking that we should mention _why_ this method exists and what makes it different from the other one.

2024-04-29 18:23 UTC, gmlewis requested changes
Thank you, @Matthew-Reidy !
One tiny nit so we have complete sentences in our godocs, otherwise LGTM.

2024-04-29 18:23 UTC, gmlewis commented on github/apps.go
> +// differs from CreateInstallationToken by taking InstallationTokenListRepoOptions as a parameter which does not omit RepositoryIDs if that field is nil or an empty array.
nit: "differs" => "It differs"

2024-04-29 18:38 UTC, Matthew-Reidy commented on github/apps.go
> +// differs from CreateInstallationToken by taking InstallationTokenListRepoOptions as a parameter which does not omit RepositoryIDs if that field is nil or an empty array.
done

2024-04-29 19:04 UTC, gmlewis approved these changes
Thank you, @Matthew-Reidy !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-04-29 21:16 UTC, be0x74a approved these changes

2024-04-29 21:27 UTC, gmlewis commented
Thank you, @be0x74a !
Merging.

2024-04-29 21:28 UTC, merged