Add support for filepath repository rules
google/go-github pull request #3233
Opened 2024-08-11 16:49 UTC by grahamhar

This is an attempt to add support for file_path_restriction in repository rules. It will implement #3231

2024-08-12 00:59 UTC, gmlewis requested changes
Thank you, @grahamhar!
Just a couple minor tweaks, please, then we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2024-08-12 13:05 UTC, grahamhar commented on github/repos_rules.go
> +// BypassActor represents a bypass actor object.
done

2024-08-12 13:52 UTC, gmlewis approved these changes
Thank you, @grahamhar!
In the future, please don't force-push in this repo as it makes code reviews more challenging. For this PR it was no big deal, but when the PRs get bigger, it becomes an issue.  We always squash-and-merge PRs anyway, so there is no need for a force-push. Thanks.

LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-08-19 07:18 UTC, tomfeigin approved these changes
LGTM

2024-08-19 11:01 UTC, gmlewis commented
Thank you, @tomfeigin !
Merging.

2024-08-19 11:02 UTC, merged

2024-08-20 18:57 UTC, grahamhar commented
@gmlewis sorry to trouble you but when is the next release due?

2024-08-20 19:40 UTC, gmlewis commented
> @gmlewis sorry to trouble you but when is the next release due?

No troubles.  It looks like we are due for a roughly-monthly release so I will try to get this done by tonight (EDT).

2024-08-21 03:01 UTC, gmlewis commented
> @gmlewis sorry to trouble you but when is the next release due?

Release completed: https://github.com/google/go-github/releases/tag/v64.0.0