feat: implement organization role assignments for both users and teams
google/go-github pull request #3281
Opened 2024-09-21 17:09 UTC by felixlut

resolves #3280

2024-09-21 17:21 UTC, felixlut commented
While working on this I noticed that the file naming is slightly off from how GitHub structures their API:s. There's a difference between [repository roles](https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/custom-roles?apiVersion=2022-11-28) and [organization roles](https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/organization-roles?apiVersion=2022-11-28), but currently the `orgs_custom_roles.go` file is dealing with both (even before my changes). It should probably be split up into ``orgs_repo_roles.go`` and ``orgs_org_roles.go`` (or maybe flip the order to `orgs_role_{org/repo}.go` to keep the files "closer together"), similarily to https://github.com/integrations/terraform-provider-github/issues/2224. 

Leaving it up to the reviewer to decide if this should be done in this PR directly or in a separate later

2024-09-21 19:28 UTC, gmlewis commented
> Leaving it up to the reviewer to decide if this should be done in this PR directly or in a separate one later

Please perform the reorganization in your next PR.  Thank you!

2024-09-21 19:32 UTC, gmlewis requested changes
Thank you, @felixlut !
Just a few minor tweaks, please, then we should be ready for a second LGTM+Approval from any other contributor to this repo.

2024-09-21 19:32 UTC, gmlewis commented on github/orgs_custom_roles.go
> +func (s *OrganizationsService) AssignOrgRoleToTeam(ctx context.Context, org string, teamSlug string, roleID int64) (*Response, error) {
```suggestion
func (s *OrganizationsService) AssignOrgRoleToTeam(ctx context.Context, org, teamSlug string, roleID int64) (*Response, error) {
```

2024-09-21 19:32 UTC, gmlewis commented on github/orgs_custom_roles.go
> +func (s *OrganizationsService) RemoveOrgRoleFromTeam(ctx context.Context, org string, teamSlug string, roleID int64) (*Response, error) {
```suggestion
func (s *OrganizationsService) RemoveOrgRoleFromTeam(ctx context.Context, org, teamSlug string, roleID int64) (*Response, error) {
```

2024-09-21 19:32 UTC, gmlewis commented on github/orgs_custom_roles.go
> +func (s *OrganizationsService) AssignOrgRoleToUser(ctx context.Context, org string, username string, roleID int64) (*Response, error) {
```suggestion
func (s *OrganizationsService) AssignOrgRoleToUser(ctx context.Context, org, username string, roleID int64) (*Response, error) {
```

2024-09-21 19:32 UTC, gmlewis commented on github/orgs_custom_roles.go
> +// RemoveOrgRoleFromUser removes an existing organization role assignment to a user in this organization.
```suggestion
// RemoveOrgRoleFromUser removes an existing organization role assignment from a user in this organization.
```

2024-09-21 19:32 UTC, gmlewis commented on github/orgs_custom_roles.go
> +// RemoveOrgRoleFromTeam removes an existing organization role assignment to a team in this organization.
```suggestion
// RemoveOrgRoleFromTeam removes an existing organization role assignment from a team in this organization.
```

2024-09-21 19:32 UTC, gmlewis commented on github/orgs_custom_roles.go
> +func (s *OrganizationsService) RemoveOrgRoleFromUser(ctx context.Context, org string, username string, roleID int64) (*Response, error) {
```suggestion
func (s *OrganizationsService) RemoveOrgRoleFromUser(ctx context.Context, org, username string, roleID int64) (*Response, error) {
```

2024-09-22 08:47 UTC, felixlut commented
@gmlewis done!

2024-09-22 21:14 UTC, gmlewis approved these changes
Thank you, @felixlut !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-09-23 06:03 UTC, tomfeigin approved these changes
LGTM

2024-09-23 13:40 UTC, gmlewis commented
Thank you, @tomfeigin !
Merging.

2024-09-23 13:40 UTC, merged