refactor: Simplify temp file creation in tests
google/go-github pull request #3290
Opened 2024-09-24 14:25 UTC by alexandear

The PR simplifies the `openTestFile` function logic by leveraging [`T.TempDir`](https://pkg.go.dev/testing#T.TempDir).

2024-09-24 15:13 UTC, gmlewis requested changes
Thank you, @alexandear !
Now that you are passing `t` here, what do you think about making this a `t.Helper`?

2024-09-24 15:13 UTC, gmlewis commented on github/github_test.go
> +	fname := filepath.Join(t.TempDir(), name)
```suggestion
	t.Helper()
	fname := filepath.Join(t.TempDir(), name)
```

2024-09-24 16:03 UTC, alexandear commented on github/github_test.go
> +	fname := filepath.Join(t.TempDir(), name)
added `t.Helper()`

2024-09-25 00:48 UTC, gmlewis approved these changes
Thank you, @alexandear .
LGTM.  (In the future, please don't force-push in this repo as we always squash-and-merge anyway... it makes reviewing changes easier since the last review. Thanks.)

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-10-01 07:08 UTC, tomfeigin approved these changes
LGTM

2024-10-01 10:51 UTC, gmlewis commented
Thanks you, @tomfeigin !
Merging.

2024-10-01 10:51 UTC, merged