chore: refactor org_custom_roles.go strucutre into multiple files
google/go-github pull request #3291
Opened 2024-09-24 16:20 UTC by felixlut

2024-09-25 00:54 UTC, gmlewis requested changes
Thank you, @felixlut !
Any time a new file is created, we bump the copyright year to the current year, but if a file is renamed or otherwise edited, we leave the copyright year alone... 
So just a couple minor nits, please, then we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2024-09-25 00:54 UTC, gmlewis commented on github/orgs_custom_repository_roles.go
> +// Copyright 2022 The go-github AUTHORS. All rights reserved.
```suggestion
// Copyright 2024 The go-github AUTHORS. All rights reserved.
```

2024-09-25 00:54 UTC, gmlewis commented on github/orgs_custom_repository_roles_test.go
> +// Copyright 2022 The go-github AUTHORS. All rights reserved.
```suggestion
// Copyright 2024 The go-github AUTHORS. All rights reserved.
```

2024-09-26 11:57 UTC, gmlewis approved these changes
Thank you, @felixlut !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-10-01 07:06 UTC, tomfeigin approved these changes
LGTM

2024-10-01 10:57 UTC, gmlewis commented
Thank you, @tomfeigin !
Merging.

2024-10-01 10:57 UTC, merged