refactor: Do not call teardown manually in tests
google/go-github pull request #3293
Opened 2024-09-24 16:38 UTC by alexandear

The PR refactors `setup` function by passing `*testing.T` parameter and calling `t.Cleanup(server.Close)` inside. So a test that using `setup` doesn't need to call manually `teardown`.

This leads to removal of 1319 code lines in tests.

2024-09-25 01:09 UTC, gmlewis requested changes
Thank you, @alexandear !
One important change, please, then we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2024-09-25 01:09 UTC, gmlewis commented on scrape/scrape_test.go
> +	return client, mux
```suggestion
	t.Cleanup(server.Close)

	return client, mux
```

2024-09-25 11:04 UTC, alexandear commented on scrape/scrape_test.go
> +	return client, mux
Thanks.

2024-09-25 11:43 UTC, gmlewis approved these changes
Thank you, @alexandear !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-10-01 07:16 UTC, tomfeigin approved these changes
LGTM

2024-10-01 11:00 UTC, gmlewis commented
Thank you, @tomfeigin !
Merging.

2024-10-01 15:52 UTC, closed without merging