Copilot Organization Summary
google/go-github pull request #3318
Opened 2024-10-09 12:37 UTC by claystation

Github has a Rest API to get the usage summary of Copilot within the organization. This PR implements the functionality to fetch that data.
API Docs: [Here](https://docs.github.com/en/rest/copilot/copilot-usage?apiVersion=2022-11-28#get-a-summary-of-copilot-usage-for-organization-members)

Please let me know what you think!

2024-10-09 14:08 UTC, gmlewis requested changes
Thank you, @claystation !
Just a few tweaks, please, then we should be ready for a second LGTM+Approval from any other contributor to this repo (and signed CLA) before merging.

2024-10-09 14:08 UTC, gmlewis commented on github/copilot.go
> +type CopilotUsageSummaryListOptions struct {
All new exported structs need Godoc-style comments complete with punctuation (here and on lines 74 and 84 below).

For example:

```go
// CopilotUsageSummaryListOptions specifies optional parameters to the
// CopilotService.GetOrganizationUsage method.
```

2024-10-09 14:08 UTC, gmlewis commented on github/copilot.go
> +	Until time.Time `url:"until,omitempty"`
```suggestion
	Since *time.Time `url:"since,omitempty"`
	Until *time.Time `url:"until,omitempty"`
```

2024-10-09 14:08 UTC, gmlewis commented on github/copilot.go
> +// GetOrganizationUsage gets daily breakdown of aggregated usage metrics for Copilot completions and Copilot Chat in the IDE across an organization
```suggestion
// GetOrganizationUsage gets daily breakdown of aggregated usage metrics for Copilot completions and Copilot Chat in the IDE across an organization.
```

2024-10-09 14:08 UTC, gmlewis commented on github/copilot_test.go
> +	client, mux, _ := setup(t)
```suggestion
	t.Parallel()
	client, mux, _ := setup(t)
```

2024-10-10 08:18 UTC, claystation commented
@gmlewis i will close this PR due to CLA signing issues. I opened #3321 which also contains a commit with the requested changes. Please review that one, i hope it should be good!

2024-10-10 08:18 UTC, closed without merging