feat: Support Code Security Configurations API
google/go-github pull request #3319
Opened 2024-10-09 19:35 UTC by maditya

This PR implements Code Security Configurations APIs as defined at https://docs.github.com/en/rest/code-security/configurations?apiVersion=2022-11-28

Fixes https://github.com/google/go-github/issues/3211

2024-10-09 20:28 UTC, gmlewis requested changes
Thank you, @maditya!
Just a few tweaks, and please remember to run `go generate ./...` as mentioned in step 4 of CONTRIBUTING.md and push (not force-push) the changes to this PR.
We then should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2024-10-09 20:28 UTC, gmlewis commented on github/orgs_codesecurity_configurations.go
> +package github
```suggestion
// Copyright 2024 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package github
```

2024-10-09 20:28 UTC, gmlewis commented on github/orgs_codesecurity_configurations_test.go
> +package github
```suggestion
// Copyright 2024 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package github
```

2024-10-09 20:28 UTC, gmlewis commented on github/orgs_codesecurity_configurations.go
> +	LabeledRunners bool `json:"labeled_runners,omitempty"`
```suggestion
	LabeledRunners *bool `json:"labeled_runners,omitempty"`
```

2024-10-09 20:28 UTC, gmlewis commented on github/orgs_codesecurity_configurations.go
> +func (s *OrganizationsService) GetCodeSecurityConfigurationForRepository(ctx context.Context, org string, repo string) (*RepositoryCodeSecurityConfiguration, *Response, error) {
```suggestion
func (s *OrganizationsService) GetCodeSecurityConfigurationForRepository(ctx context.Context, org, repo string) (*RepositoryCodeSecurityConfiguration, *Response, error) {
```

2024-10-09 22:16 UTC, maditya commented
@gmlewis Thanks!
I tried and fixed `go generate ./...` which updated a bunch of other files.
But `metadata` script is failing -

```
ambiguous operation "GET /user/{user_id}" could match any of: [GET /user/{account_id} GET /user/{user_id}]
github/github.go:8: running "../script/metadata.sh": exit status 1
```
Any idea how to address it? Doesn't seem related to the new API.

2024-10-10 01:26 UTC, gmlewis commented
> Any idea how to address it?

Hmmm... a lot more files changed than I expected.
It looks like you may have locally updated the OpenAPI specs, which is typically done by a maintainer of the repo.

We have two options:
1. revert the changes to all the files except your original two, then run `go generate ./...` 
2. wait for another PR to update all the OpenAPI stuff and fix all the errors you are seeing

I think option 1 is probably better since option 2 may take a while, and I'm currently monitoring a hurricane locally.

2024-10-10 05:31 UTC, maditya commented
>  revert the changes to all the files except your original two, then run go generate ./...

Done. Note that `go generate ./...` updates some other files, namely `github/admin_users.go`, `github/github-accessors.go` and `github/github-accessors_test.go` and will fail until `openapi_operations.yaml` is updated. I get these errors: 
```
could not find operation "GET /orgs/{org}/code-security/configurations" in openapi_operations.yaml
could not find operation "POST /orgs/{org}/code-security/configurations" in openapi_operations.yaml
could not find operation "GET /orgs/{org}/code-security/configurations/defaults" in openapi_operations.yaml
could not find operation "DELETE /orgs/{org}/code-security/configurations/detach" in openapi_operations.yaml
could not find operation "GET /orgs/{org}/code-security/configurations/{configuration_id}" in openapi_operations.yaml
could not find operation "PATCH /orgs/{org}/code-security/configurations/{configuration_id}" in openapi_operations.yaml
could not find operation "DELETE /orgs/{org}/code-security/configurations/{configuration_id}" in openapi_operations.yaml
could not find operation "POST /orgs/{org}/code-security/configurations/{configuration_id}/attach" in openapi_operations.yaml
could not find operation "PUT /orgs/{org}/code-security/configurations/{configuration_id}/defaults" in openapi_operations.yaml
could not find operation "GET /orgs/{org}/code-security/configurations/{configuration_id}/repositories" in openapi_operations.yaml
could not find operation "GET /repos/{owner}/{repo}/code-security-configuration" in openapi_operations.yaml
github/github.go:8: running "../script/metadata.sh": exit status 1
```

2024-10-10 12:26 UTC, gmlewis commented
> Note that `go generate ./...` updates some other files

That is really strange. 
`go generate ./...` should only update three files (as needed):

* github/github-accessors.go 
* github/github-accessors_test.go
* github/github-stringify_test.go

I'm going to make a new branch locally with just your changes to your two files and run `go generate ./...` and see what happens for me and report back.

2024-10-10 12:39 UTC, gmlewis commented
> I'm going to make a new branch locally with just your changes to your two files and run `go generate ./...` and see what happens for me and report back.

Ah, I see what is going on now.  You are adding support for new operations not yet defined in our local OpenAPI yaml.

This section in CONTRIBUTING.md is pertinent to you:

> ### openapi_operations.yaml
> 
> Most contributors won't need to interact with `openapi_operations.yaml`, but it
> may be useful to know what it is. Its sections are:
> ...

So you can either attempt to update it yourself by running `script/metadata.sh update-openapi` and then work out any issues you find, or I can do that in a separate PR.  Which would you prefer?

2024-10-10 12:55 UTC, gmlewis commented
EDIT: I've gone ahead and created #3322 which you should be able to merge into your PR (from master once I merge it), which should make the rest of this PR easier to finish.

It looks like (in addition to the code generation), the tests need to have more coverage by using existing test helper methods like `testBadOptions` and `testNewRequestAndDoFailure`. You can see these in the GitHub UI.

2024-10-10 16:33 UTC, gmlewis approved these changes
Thank you, @maditya !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-10-14 10:32 UTC, gmlewis commented
Thank you, @tomfeigin !
Merging.

2024-10-14 10:35 UTC, merged