feat!: rename code scanning params from plural to singular
google/go-github pull request #3331
Opened 2024-10-21 16:52 UTC by ihor-hrytskiv

2024-10-21 17:02 UTC, gmlewis requested changes
Thank you, @ihor-hrytskiv.
One minor suggestion, then we should be ready for a second LGTM+Approval from any other contributor to this repo before merging.

2024-10-21 17:02 UTC, gmlewis commented on github/repos_rules.go
> +// RuleRequiredCodeScanningTool represents the RequiredCodeScanningTools for the RequiredCodeScanningParameters object.
We might as well go all in and update the comment too, agreed?
Maybe something like this?

```suggestion
// RuleRequiredCodeScanningTool represents a single required code-scanning tool for the RequiredCodeScanningParameters object.
```

2024-10-21 18:36 UTC, gmlewis approved these changes
Thank you, @ihor-hrytskiv !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-10-22 05:21 UTC, ihor-hrytskiv commented
@air-hand Could you review please?

2024-10-22 09:33 UTC, air-hand approved these changes
LGTM

2024-10-22 12:25 UTC, gmlewis commented
Thank you, @air-hand !
Merging.

2024-10-22 12:25 UTC, merged