Add opt-in rate limit support on endpoints returning 302s
google/go-github pull request #3411
Opened 2024-12-31 14:54 UTC by wmouchere

Fixes #3406

Some endpoints of the GitHub HTTP API return a 302 response in successful scenarios, often to redirect to archives or artifacts download links. Because the `net/http` client usually follows 302s when calling `Do`, we instead currently use the `RoundTripper` directly for those endpoint to check after each call if the current redirection is a 302. The problem is that the library supports rate limit headers only in the `Do` type of calls.

This PR adds an opt-in feature flag to enable rate limit headers support on those endpoints which end with a 302 redirection. I refactored `Client` a bit to share the core `BareDo` logic between calls that care about redirection details and call that don't. I added an unexported `bareDoUntilFound` method that behaves similarly to the old `roundTripWithOptionalFollowRedirect` but with all the rate limit and error handling that other endpoints have.

2024-12-31 15:21 UTC, gmlewis requested changes
Thank you, @wmouchere - this is looking great!
I'm requesting one minor change across all your new methods, please.
Also, if you could increase the code coverage for the new methods (see Codecov feedback in the GitHub UI), that would be great, but not absolutely necessary, as the uncovered cases are indeed going to be rare error paths.

Additionally, I'm noticing that you use `%d` and `%s` in format strings, and it is very common in idiomatic Go to simply use `%v` everywhere unless there is a strong need to do otherwise (which then catches the eye as an indication that something unusual is going on here).  It would be nice (but not required) if you switch to `%v` if you don't mind.

2024-12-31 15:21 UTC, gmlewis commented on github/actions_artifacts.go
> +	return nil, resp, fmt.Errorf("unexpected status code: %s", resp.Status)
For this file and all the other `...WithRateLimit` methods, could we place make the "happy path" the one that flows to the end of the method, as per idiomatic Go?

```suggestion
	// If we didn't receive a valid Location in a 302 response
	if url == nil {
		return nil, resp, fmt.Errorf("unexpected status code: %v", resp.Status)
	}

	return url, resp, nil
```

2024-12-31 17:25 UTC, gmlewis approved these changes
This looks fantastic, @wmouchere !
Beautifully well-done - thank you!
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

2024-12-31 17:26 UTC, wmouchere commented
Thanks a lot for the quick review @gmlewis! 
- Changes you mentioned on the happy path flow are done 👍 
- I should have updated all the `%s` I added to `%v`, but left the `%d` where its used to format a http status. I noticed that this was the pattern used in most places in the library.
- I did my best to increase coverage by testing handling of unexpected status codes. I would have wanted to test invalid `Location` headers but `net/http` actually validates them upstream which changes the flow a bit and makes it hard to test.

2025-01-02 16:15 UTC, Letiste approved these changes

2025-01-02 17:00 UTC, gmlewis commented
Thank you, @Letiste !
Merging.

2025-01-02 17:00 UTC, merged